#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103051_BP

#include "Basic.hpp"

#include "Hero_1030_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103051_BP.Ability_103051_BP_C
// 0x0000 (0x2768 - 0x2768)
class UAbility_103051_BP_C final : public UAbility_103051
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103051_BP_C">();
	}
	static class UAbility_103051_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103051_BP_C>();
	}
};

}

