#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101881_BP

#include "Basic.hpp"

#include "Hero_1018_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101881_BP.Ability_101881_BP_C
// 0x0000 (0x26D0 - 0x26D0)
class UAbility_101881_BP_C final : public UAbility_101881
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101881_BP_C">();
	}
	static class UAbility_101881_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101881_BP_C>();
	}
};

}

