#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103751_BP

#include "Basic.hpp"

#include "PyAbility_103751_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103751_BP.Ability_103751_BP_C
// 0x0000 (0x2768 - 0x2768)
class UAbility_103751_BP_C final : public UPyAbility_103751
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103751_BP_C">();
	}
	static class UAbility_103751_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103751_BP_C>();
	}
};

}

