#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101123_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101123_BP.Ability_101123_BP_C
// 0x0000 (0x27E8 - 0x27E8)
class UAbility_101123_BP_C final : public UAbility_113
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101123_BP_C">();
	}
	static class UAbility_101123_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101123_BP_C>();
	}
};

}

