#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_104531_BP

#include "Basic.hpp"

#include "PyAbility_104531_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104531_BP.Ability_104531_BP_C
// 0x0000 (0x25A8 - 0x25A8)
class UAbility_104531_BP_C final : public UPyAbility_104531
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104531_BP_C">();
	}
	static class UAbility_104531_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104531_BP_C>();
	}
};

}

