#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101421_BP

#include "Basic.hpp"

#include "Hero_1014_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101421_BP.Ability_101421_BP_C
// 0x0000 (0x2658 - 0x2658)
class UAbility_101421_BP_C final : public UAbility_101421
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101421_BP_C">();
	}
	static class UAbility_101421_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101421_BP_C>();
	}
};

}

