#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_104766_BP

#include "Basic.hpp"

#include "PyAbility_104763_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104766_BP.Ability_104766_BP_C
// 0x0000 (0x2610 - 0x2610)
class UAbility_104766_BP_C final : public UPyAbility_104763_New
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104766_BP_C">();
	}
	static class UAbility_104766_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104766_BP_C>();
	}
};

}

