#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101721_BP

#include "Basic.hpp"

#include "PyAbility_101721_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101721_BP.Ability_101721_BP_C
// 0x0000 (0x2588 - 0x2588)
class UAbility_101721_BP_C final : public UPyAbility_101721
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101721_BP_C">();
	}
	static class UAbility_101721_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101721_BP_C>();
	}
};

}

