#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102743_BP

#include "Basic.hpp"

#include "PyAbility_102743_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102743_BP.Ability_102743_BP_C
// 0x0000 (0x2588 - 0x2588)
class UAbility_102743_BP_C final : public UPyAbility_102743
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102743_BP_C">();
	}
	static class UAbility_102743_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102743_BP_C>();
	}
};

}

