#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_104641_BP

#include "Basic.hpp"

#include "Hero_1046_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104641_BP.Ability_104641_BP_C
// 0x0000 (0x2720 - 0x2720)
class UAbility_104641_BP_C final : public UAbility_104641
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104641_BP_C">();
	}
	static class UAbility_104641_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104641_BP_C>();
	}
};

}

