#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_105161_BP

#include "Basic.hpp"

#include "PyAbility_105161_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105161_BP.Ability_105161_BP_C
// 0x0000 (0x2C50 - 0x2C50)
class UAbility_105161_BP_C final : public UPyAbility_105161
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_105161_BP_C">();
	}
	static class UAbility_105161_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105161_BP_C>();
	}
};

}

