#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102661_BP

#include "Basic.hpp"

#include "PyAbility_102661_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102661_BP.Ability_102661_BP_C
// 0x0000 (0x25F0 - 0x25F0)
class UAbility_102661_BP_C final : public UPyAbility_102661
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102661_BP_C">();
	}
	static class UAbility_102661_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102661_BP_C>();
	}
};

}

