#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102301_BP

#include "Basic.hpp"

#include "PyAbility_102301_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102301_BP.Ability_102301_BP_C
// 0x0000 (0x2610 - 0x2610)
class UAbility_102301_BP_C final : public UPyAbility_102301
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102301_BP_C">();
	}
	static class UAbility_102301_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102301_BP_C>();
	}
};

}

