#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103921_BP

#include "Basic.hpp"

#include "PyAbility_103921_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103921_BP.Ability_103921_BP_C
// 0x0000 (0x2598 - 0x2598)
class UAbility_103921_BP_C final : public UPyAbility_103921
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103921_BP_C">();
	}
	static class UAbility_103921_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103921_BP_C>();
	}
};

}

