#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101621_BP

#include "Basic.hpp"

#include "PyAbility_101621_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101621_BP.Ability_101621_BP_C
// 0x0000 (0x2598 - 0x2598)
class UAbility_101621_BP_C final : public UPyAbility_101621
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101621_BP_C">();
	}
	static class UAbility_101621_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101621_BP_C>();
	}
};

}

