#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102322_BP

#include "Basic.hpp"

#include "PyAbility_102322_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102322_BP.Ability_102322_BP_C
// 0x0000 (0x26B0 - 0x26B0)
class UAbility_102322_BP_C final : public UPyAbility_102322
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102322_BP_C">();
	}
	static class UAbility_102322_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102322_BP_C>();
	}
};

}

