#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102341_BP

#include "Basic.hpp"

#include "PyAbility_102341_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102341_BP.Ability_102341_BP_C
// 0x0000 (0x2600 - 0x2600)
class UAbility_102341_BP_C final : public UPyAbility_102341
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102341_BP_C">();
	}
	static class UAbility_102341_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102341_BP_C>();
	}
};

}

