#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_105071_BP

#include "Basic.hpp"

#include "PyAbility_105071_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105071_BP.Ability_105071_BP_C
// 0x0000 (0x2630 - 0x2630)
class UAbility_105071_BP_C final : public UPyAbility_105071
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_105071_BP_C">();
	}
	static class UAbility_105071_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105071_BP_C>();
	}
};

}

