#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_104556_BP

#include "Basic.hpp"

#include "PyAbility_104553_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104556_BP.Ability_104556_BP_C
// 0x0000 (0x2598 - 0x2598)
class UAbility_104556_BP_C final : public UPyAbility_104553
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104556_BP_C">();
	}
	static class UAbility_104556_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104556_BP_C>();
	}
};

}

