#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102481_BP

#include "Basic.hpp"

#include "PyAbility_102481_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102481_BP.Ability_102481_BP_C
// 0x0000 (0x5C00 - 0x5C00)
class UAbility_102481_BP_C final : public UPyAbility_102481
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102481_BP_C">();
	}
	static class UAbility_102481_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102481_BP_C>();
	}
};

}

