#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_104831_BP

#include "Basic.hpp"

#include "PyAbility_104831_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104831_BP.Ability_104831_BP_C
// 0x0000 (0x25C8 - 0x25C8)
class UAbility_104831_BP_C final : public UPyAbility_104831
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104831_BP_C">();
	}
	static class UAbility_104831_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104831_BP_C>();
	}
};

}

