#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102581_BP

#include "Basic.hpp"

#include "PyAbility_102581_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102581_BP.Ability_102581_BP_C
// 0x0000 (0x25E0 - 0x25E0)
class UAbility_102581_BP_C final : public UPyAbility_102581
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102581_BP_C">();
	}
	static class UAbility_102581_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102581_BP_C>();
	}
};

}

