#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102571_BP

#include "Basic.hpp"

#include "PyAbility_102571_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102571_BP.Ability_102571_BP_C
// 0x0000 (0x25D0 - 0x25D0)
class UAbility_102571_BP_C final : public UPyAbility_102571
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102571_BP_C">();
	}
	static class UAbility_102571_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102571_BP_C>();
	}
};

}

