#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_211_BP

#include "Basic.hpp"

#include "PyAbility_211_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_211_BP.Ability_211_BP_C
// 0x0000 (0x25A0 - 0x25A0)
class UAbility_211_BP_C final : public UPyAbility_211
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_211_BP_C">();
	}
	static class UAbility_211_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_211_BP_C>();
	}
};

}

