#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_213_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_213_BP.Ability_213_BP_C
// 0x0000 (0x25B0 - 0x25B0)
class UAbility_213_BP_C final : public UAbility_213
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_213_BP_C">();
	}
	static class UAbility_213_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_213_BP_C>();
	}
};

}

