#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102692_BP

#include "Basic.hpp"

#include "PySynergy_100008_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102692_BP.Ability_102692_BP_C
// 0x0000 (0x25B0 - 0x25B0)
class UAbility_102692_BP_C final : public UPyAbility_10000802
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102692_BP_C">();
	}
	static class UAbility_102692_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102692_BP_C>();
	}
};

}

