#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101491_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101491_BP.Ability_101491_BP_C
// 0x0000 (0x2590 - 0x2590)
class UAbility_101491_BP_C final : public UAbility_108
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101491_BP_C">();
	}
	static class UAbility_101491_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101491_BP_C>();
	}
};

}

