#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103861_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103861_BP.Ability_103861_BP_C
// 0x0000 (0x25E0 - 0x25E0)
class UAbility_103861_BP_C final : public UAbility_111
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103861_BP_C">();
	}
	static class UAbility_103861_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103861_BP_C>();
	}
};

}

