#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102742_BP

#include "Basic.hpp"

#include "PyAbility_102742_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102742_BP.Ability_102742_BP_C
// 0x0000 (0x2598 - 0x2598)
class UAbility_102742_BP_C final : public UPyAbility_102742
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102742_BP_C">();
	}
	static class UAbility_102742_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102742_BP_C>();
	}
};

}

