#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103731_BP

#include "Basic.hpp"

#include "PyAbility_103731_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103731_BP.Ability_103731_BP_C
// 0x0000 (0x2590 - 0x2590)
class UAbility_103731_BP_C final : public UPyAbility_103731
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103731_BP_C">();
	}
	static class UAbility_103731_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103731_BP_C>();
	}
};

}

