#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103311_BP

#include "Basic.hpp"

#include "PyAbility_103311_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103311_BP.Ability_103311_BP_C
// 0x0000 (0x26A0 - 0x26A0)
class UAbility_103311_BP_C final : public UPyAbility_103311
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103311_BP_C">();
	}
	static class UAbility_103311_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103311_BP_C>();
	}
};

}

