#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101431_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101431_BP.Ability_101431_BP_C
// 0x0000 (0x25D0 - 0x25D0)
class UAbility_101431_BP_C final : public UAbility_105
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101431_BP_C">();
	}
	static class UAbility_101431_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101431_BP_C>();
	}
};

}

