#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103616_BP

#include "Basic.hpp"

#include "PyAbility_103616_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103616_BP.Ability_103616_BP_C
// 0x0000 (0x2588 - 0x2588)
class UAbility_103616_BP_C final : public UPyAbility_103616
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103616_BP_C">();
	}
	static class UAbility_103616_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103616_BP_C>();
	}
};

}

