#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_101852_BP

#include "Basic.hpp"

#include "Ability_101851_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101852_BP.Ability_101852_BP_C
// 0x0000 (0x2598 - 0x2598)
class UAbility_101852_BP_C final : public UAbility_101851_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101852_BP_C">();
	}
	static class UAbility_101852_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101852_BP_C>();
	}
};

}

