#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102962_BP

#include "Basic.hpp"

#include "PyAbility_102961_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102962_BP.Ability_102962_BP_C
// 0x0000 (0x2590 - 0x2590)
class UAbility_102962_BP_C final : public UPyAbility_102961
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102962_BP_C">();
	}
	static class UAbility_102962_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102962_BP_C>();
	}
};

}

