#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_105121_BP

#include "Basic.hpp"

#include "PyAbility_105121_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105121_BP.Ability_105121_BP_C
// 0x0000 (0x2590 - 0x2590)
class UAbility_105121_BP_C final : public UPyAbility_105121
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_105121_BP_C">();
	}
	static class UAbility_105121_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105121_BP_C>();
	}
};

}

