#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102255_BP

#include "Basic.hpp"

#include "Hero_1022_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102255_BP.Ability_102255_BP_C
// 0x0000 (0x2598 - 0x2598)
class UAbility_102255_BP_C final : public UAbility_102255
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102255_BP_C">();
	}
	static class UAbility_102255_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102255_BP_C>();
	}
};

}

