#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103701_BP

#include "Basic.hpp"

#include "PyAbility_103701_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103701_BP.Ability_103701_BP_C
// 0x0000 (0x2640 - 0x2640)
class UAbility_103701_BP_C final : public UPyAbility_103701
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103701_BP_C">();
	}
	static class UAbility_103701_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103701_BP_C>();
	}
};

}

