#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_104161_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyAbility_104161_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104161_BP.Ability_104161_BP_C
// 0x0008 (0x29A0 - 0x2998)
class UAbility_104161_BP_C final : public UPyAbility_104161
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2998(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Ability_104161_BP(int32 EntryPoint);
	void SetAbilityExtraWidget_1(class UUserWidget* InExtraWidget);
	void SetAbilityStatusWidget_1(class UUserWidget* InUserWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104161_BP_C">();
	}
	static class UAbility_104161_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104161_BP_C>();
	}
};

}

