#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103061_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyAbility_103061_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103061_BP.Ability_103061_BP_C
// 0x0008 (0x25A0 - 0x2598)
class UAbility_103061_BP_C final : public UPyAbility_103061
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2598(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Ability_103061_BP(int32 EntryPoint);
	void SetAbilityExtraWidget_1(class UUserWidget* InExtraWidget);
	void SetAbilityStatusWidget_1(class UUserWidget* InUserWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103061_BP_C">();
	}
	static class UAbility_103061_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103061_BP_C>();
	}
};

}

