#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_102511_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102511_BP.Ability_102511_BP_C
// 0x10C0 (0x3650 - 0x2590)
class UAbility_102511_BP_C final : public UAbility_108
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2590(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	uint8                                         Pad_2598[0x8];                                     // 0x2598(0x0008)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FSelectTaskParam                       选取参数;                                          // 0x25A0(0x10A0)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class AActor*                                 Target;                                            // 0x3640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AE_OnAbilityInitialized();
	void ExecuteUbergraph_Ability_102511_BP(int32 EntryPoint);
	void K2_ActivateAbility();
	void MissileEventNotify();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102511_BP_C">();
	}
	static class UAbility_102511_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102511_BP_C>();
	}
};

}

