#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Ability_103342_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103342_BP.Ability_103342_BP_C
// 0x0020 (0x25A8 - 0x2588)
class UAbility_103342_BP_C final : public UMarvelGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2588(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                跳跃速度;                                          // 0x2590(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool CanActivate();
	void ExecuteUbergraph_Ability_103342_BP(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnCompletedDelegate_743C80F04360F8F677D92F8E6EA3F17A(const struct FGameplayTag& TriggerNotifyTagEventDelegate__DelegateSignature_EventTag);
	void OnTriggerEvent_743C80F04360F8F677D92F8E6EA3F17A(const struct FGameplayTag& TriggerNotifyTagEventDelegate__DelegateSignature_EventTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103342_BP_C">();
	}
	static class UAbility_103342_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103342_BP_C>();
	}
};

}

