#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AIMoveControl_1039_Ultimate

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIMoveControl_1039_Ultimate.AIMoveControl_1039_Ultimate_C
// 0x0000 (0x00B8 - 0x00B8)
class UAIMoveControl_1039_Ultimate_C final : public UAIAbilityMoveControlLogic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIMoveControl_1039_Ultimate_C">();
	}
	static class UAIMoveControl_1039_Ultimate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIMoveControl_1039_Ultimate_C>();
	}
};

}

