#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AIMoveControl_StormUltimate

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIMoveControl_StormUltimate.AIMoveControl_StormUltimate_C
// 0x0000 (0x00B8 - 0x00B8)
class UAIMoveControl_StormUltimate_C final : public UAIAbilityMoveControlLogic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIMoveControl_StormUltimate_C">();
	}
	static class UAIMoveControl_StormUltimate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIMoveControl_StormUltimate_C>();
	}
};

}

