#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AIMoveControl_ScarletWitchUltimate

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIMoveControl_ScarletWitchUltimate.AIMoveControl_ScarletWitchUltimate_C
// 0x0000 (0x00B8 - 0x00B8)
class UAIMoveControl_ScarletWitchUltimate_C final : public UAIAbilityMoveControlLogic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIMoveControl_ScarletWitchUltimate_C">();
	}
	static class UAIMoveControl_ScarletWitchUltimate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIMoveControl_ScarletWitchUltimate_C>();
	}
};

}

