#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AIMoveControl_MantisUltimate

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIMoveControl_MantisUltimate.AIMoveControl_MantisUltimate_C
// 0x0000 (0x00B8 - 0x00B8)
class UAIMoveControl_MantisUltimate_C final : public UAIAbilityMoveControlLogic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIMoveControl_MantisUltimate_C">();
	}
	static class UAIMoveControl_MantisUltimate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIMoveControl_MantisUltimate_C>();
	}
};

}

