#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AIMoveControl_Ultimate_CanSeeEnemy

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIMoveControl_Ultimate_CanSeeEnemy.AIMoveControl_Ultimate_CanSeeEnemy_C
// 0x0000 (0x00B8 - 0x00B8)
class UAIMoveControl_Ultimate_CanSeeEnemy_C final : public UAIAbilityMoveControlLogic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIMoveControl_Ultimate_CanSeeEnemy_C">();
	}
	static class UAIMoveControl_Ultimate_CanSeeEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIMoveControl_Ultimate_CanSeeEnemy_C>();
	}
};

}

