#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AISelectTarget_HulkJump

#include "Basic.hpp"

#include "PyAISelectTarget_HulkJump_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AISelectTarget_HulkJump.AISelectTarget_HulkJump_C
// 0x0000 (0x0078 - 0x0078)
class UAISelectTarget_HulkJump_C final : public UPyAISelectTarget_HulkJump
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AISelectTarget_HulkJump_C">();
	}
	static class UAISelectTarget_HulkJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAISelectTarget_HulkJump_C>();
	}
};

}

