#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AntiLag2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class AntiLag2.AntiLag2BlueprintLibrary
// 0x0000 (0x0030 - 0x0030)
class UAntiLag2BlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	bool GetAMDAntiLag2Support();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AntiLag2BlueprintLibrary">();
	}
	static class UAntiLag2BlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAntiLag2BlueprintLibrary>();
	}
};

}

