#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: AntiLag2Settings

#include "Basic.hpp"

#include "DeveloperSettings_classes.hpp"


namespace SDK
{

// Class AntiLag2Settings.AntiLag2Settings
// 0x0008 (0x0050 - 0x0048)
class UAntiLag2Settings final : public UDeveloperSettings
{
public:
	bool                                          bEnabled;                                          // 0x0048(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AntiLag2Settings">();
	}
	static class UAntiLag2Settings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAntiLag2Settings>();
	}
};

}

