#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: BTD_BlackboardDifferenceOp_BP

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTD_BlackboardDifferenceOp_BP.BTD_BlackboardDifferenceOp_BP_C
// 0x0000 (0x00E8 - 0x00E8)
class UBTD_BlackboardDifferenceOp_BP_C final : public UBTDecorator_BBDifferenceOp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTD_BlackboardDifferenceOp_BP_C">();
	}
	static class UBTD_BlackboardDifferenceOp_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTD_BlackboardDifferenceOp_BP_C>();
	}
};

}

