#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: BuffAbility_10390101_BP

#include "Basic.hpp"

#include "PyAbility_103901_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BuffAbility_10390101_BP.BuffAbility_10390101_BP_C
// 0x0000 (0x1328 - 0x1328)
class UBuffAbility_10390101_BP_C final : public UPyBuffAbility_10390101
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuffAbility_10390101_BP_C">();
	}
	static class UBuffAbility_10390101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10390101_BP_C>();
	}
};

}

