#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: BuffAbility_10256201_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BuffAbility_10256201_BP.BuffAbility_10256201_BP_C
// 0x0000 (0x1188 - 0x1188)
class UBuffAbility_10256201_BP_C final : public UMarvelBlindAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuffAbility_10256201_BP_C">();
	}
	static class UBuffAbility_10256201_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10256201_BP_C>();
	}
};

}

