#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: BuffAbility_10365101_BP

#include "Basic.hpp"

#include "Hero_1036_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BuffAbility_10365101_BP.BuffAbility_10365101_BP_C
// 0x0000 (0x1150 - 0x1150)
class UBuffAbility_10365101_BP_C final : public UBuffAbility_10365101
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuffAbility_10365101_BP_C">();
	}
	static class UBuffAbility_10365101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10365101_BP_C>();
	}
};

}

