#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: BuffAbility_103091

#include "Basic.hpp"

#include "Hero_Synergy_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BuffAbility_103091.BuffAbility_103091_C
// 0x0000 (0x12E8 - 0x12E8)
class UBuffAbility_103091_C final : public UBuffManagerAbility_100009
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuffAbility_103091_C">();
	}
	static class UBuffAbility_103091_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_103091_C>();
	}
};

}

