#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: CameraShake_101193_Grab

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_101193_Grab.CameraShake_101193_Grab_C
// 0x0000 (0x02B0 - 0x02B0)
class UCameraShake_101193_Grab_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_101193_Grab_C">();
	}
	static class UCameraShake_101193_Grab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_101193_Grab_C>();
	}
};

}

