#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: CameraShake_103561

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_103561.CameraShake_103561_C
// 0x0000 (0x02B0 - 0x02B0)
class UCameraShake_103561_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_103561_C">();
	}
	static class UCameraShake_103561_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_103561_C>();
	}
};

}

