#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: CameraShake_104891

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_104891.CameraShake_104891_C
// 0x0000 (0x02B0 - 0x02B0)
class UCameraShake_104891_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_104891_C">();
	}
	static class UCameraShake_104891_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_104891_C>();
	}
};

}

