#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: CameraShake_104521

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_104521.CameraShake_104521_C
// 0x0000 (0x02B0 - 0x02B0)
class UCameraShake_104521_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_104521_C">();
	}
	static class UCameraShake_104521_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_104521_C>();
	}
};

}

