#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Common_MVP_LightBP

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Common_MVP_LightBP.Common_MVP_LightBP_C
// 0x0018 (0x04A8 - 0x0490)
class ACommon_MVP_LightBP_C final : public AActor
{
public:
	class UDirectionalLightComponent*             Rim_Light_02;                                      // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDirectionalLightComponent*             Rim_Light_01;                                      // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Common_MVP_LightBP_C">();
	}
	static class ACommon_MVP_LightBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACommon_MVP_LightBP_C>();
	}
};

}

