#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Cue_CustomEvent

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cue_CustomEvent.Cue_CustomEvent_C
// 0x0000 (0x0288 - 0x0288)
class UCue_CustomEvent_C final : public UMarvelCueNotify_CustomEvent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cue_CustomEvent_C">();
	}
	static class UCue_CustomEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCue_CustomEvent_C>();
	}
};

}

