#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: DataflowEngine

#include "Basic.hpp"


namespace SDK::Params
{

// Function DataflowEngine.DataflowBlueprintLibrary.EvaluateTerminalNodeByName
// 0x0020 (0x0020 - 0x0000)
struct DataflowBlueprintLibrary_EvaluateTerminalNodeByName final
{
public:
	class UDataflow*                              Dataflow;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TerminalNodeName;                                  // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	class UObject*                                ResultAsset;                                       // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

