#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Effect_1105

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Effect_1105.Effect_1105_C
// 0x0000 (0x13A0 - 0x13A0)
class UEffect_1105_C final : public UMarvelGameplayEffectTemplate
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Effect_1105_C">();
	}
	static class UEffect_1105_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffect_1105_C>();
	}
};

}

