#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Grabbed_101193_BP

#include "Basic.hpp"

#include "PyAbility_101191_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Grabbed_101193_BP.Grabbed_101193_BP_C
// 0x0000 (0x1180 - 0x1180)
class UGrabbed_101193_BP_C final : public UPyAbility_AirGrab_101191
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Grabbed_101193_BP_C">();
	}
	static class UGrabbed_101193_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGrabbed_101193_BP_C>();
	}
};

}

