#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Hero_1051

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum Hero_1051.ERushState_105141
// NumValues: 0x0004
enum class ERushState_105141 : uint8
{
	Tracking                                 = 0,
	ForwardToTarget                          = 1,
	Finish                                   = 2,
	ERushState_MAX                           = 3,
};

// Enum Hero_1051.EAbilityState_105162
// NumValues: 0x0003
enum class EAbilityState_105162 : uint8
{
	Idle                                     = 0,
	Run                                      = 1,
	EAbilityState_MAX                        = 2,
};

// ScriptStruct Hero_1051.SinglePointHitResult
// 0x0178 (0x0178 - 0x0000)
struct FSinglePointHitResult final
{
public:
	struct FHitResult                             HitResult;                                         // 0x0000(0x0170)(BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	int32                                         HorizontalIndex;                                   // 0x0170(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_174[0x4];                                      // 0x0174(0x0004)(Fixing Struct Size After Last Property [ Chaos Dumper ])
};

// ScriptStruct Hero_1051.SingleRowHitResults
// 0x0010 (0x0010 - 0x0000)
struct FSingleRowHitResults final
{
public:
	TArray<struct FSinglePointHitResult>          HitResults;                                        // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// ScriptStruct Hero_1051.StoneRepInfo_105151
// 0x0070 (0x0070 - 0x0000)
struct FStoneRepInfo_105151 final
{
public:
	struct FTransform                             Transform;                                         // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         StoneRow;                                          // 0x0060(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_64[0xC];                                       // 0x0064(0x000C)(Fixing Struct Size After Last Property [ Chaos Dumper ])
};

// ScriptStruct Hero_1051.ThrowMaterialInfo_105162
// 0x0028 (0x0028 - 0x0000)
struct FThrowMaterialInfo_105162 final
{
public:
	struct FPortableMaterialSlotName              MaterialSlotName;                                  // 0x0000(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstance*                      OriginMaterial;                                    // 0x0018(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstance*                      ThrowMaterial;                                     // 0x0020(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

