#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: hero_statistics_unit

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction hero_statistics_unit.PyHeroStatisticsUnit.PyOnTakePayloadHeal
// 0x0004 (0x0004 - 0x0000)
struct PyHeroStatisticsUnit_PyOnTakePayloadHeal final
{
public:
	float                                         HealValue;                                         // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

