#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Hero_1014

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Hero_1014_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class Hero_1014.AbilityStatistics_101451
// 0x0000 (0x0088 - 0x0088)
class UAbilityStatistics_101451 final : public UTagAbilityStatistics
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AbilityStatistics_101451">();
	}
	static class UAbilityStatistics_101451* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityStatistics_101451>();
	}
};

// Class Hero_1014.AbilityStatistics_101462
// 0x0000 (0x0088 - 0x0088)
class UAbilityStatistics_101462 final : public UTagAbilityStatistics
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AbilityStatistics_101462">();
	}
	static class UAbilityStatistics_101462* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityStatistics_101462>();
	}
};

// Class Hero_1014.Config_101411
// 0x00A8 (0x0140 - 0x0098)
class UConfig_101411 final : public UMarvelAbilityConfig
{
public:
	TMap<EHealthStatus, float>                    HealthStatusLower;                                 // 0x0098(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TMap<EHealthStatus, int32>                    HealthStatusParam;                                 // 0x00E8(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         ScopeId;                                           // 0x0138(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BuffID;                                            // 0x013C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101411">();
	}
	static class UConfig_101411* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101411>();
	}
};

// Class Hero_1014.Ability_101411
// 0x1058 (0x35E0 - 0x2588)
class alignas(0x10) UAbility_101411 : public UMarvelGameplayAbility
{
public:
	uint8                                         Pad_2588[0xFB8];                                   // 0x2588(0x0FB8)(Fixing Size After Last Property [ Chaos Dumper ])
	TSet<class AActor*>                           ActiveTargets;                                     // 0x3540(0x0050)(Transient, Protected, NativeAccessSpecifierProtected)
	TMap<class AActor*, EVisibleStatus>           ActiveTargetVisibleStatus;                         // 0x3590(0x0050)(Transient, Protected, NativeAccessSpecifierProtected)

public:
	void ServerApplyEffect(const TArray<class AActor*>& Actors);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101411">();
	}
	static class UAbility_101411* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101411>();
	}
};

// Class Hero_1014.CueNotify_10141101
// 0x0028 (0x1060 - 0x1038)
class ACueNotify_10141101 : public AMarvelCueNotify_Buff
{
public:
	class AMarvelBaseCharacter*                   OwnerCharacter;                                    // 0x1038(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AMarvelBaseCharacter*                   InsCharacter;                                      // 0x1040(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConfig_101411*                         Config;                                            // 0x1048(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraComponent*                      NS_LoopFX;                                         // 0x1050(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1058[0x8];                                     // 0x1058(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	EHealthStatus GetHealthStatus(const class UMarvelAttributeSet* AttributeSet);
	void OnViewingCharacterChanged(class AMarvelBaseCharacter* ViewingTarget);
	void SetVisibleForInstigator(bool bVisibleDirectly, bool bIsBlockedBySmoke);
	void UpdatePerceiveEffect();

	void SetVisibleLevel(int32 FillColorIndex) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CueNotify_10141101">();
	}
	static class ACueNotify_10141101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACueNotify_10141101>();
	}
};

// Class Hero_1014.Config_101421
// 0x0088 (0x0120 - 0x0098)
class UConfig_101421 final : public UMarvelAbilityConfig
{
public:
	TSet<int32>                                   ExcludeDamageFromAbilities;                        // 0x0098(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FHealthConversion_101421>       HealthConversions;                                 // 0x00E8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FMarvelBuffSpecInfo>            TreatBuffSpecs;                                    // 0x00F8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGameplayTag                           SpecialSkillTag;                                   // 0x0108(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TreatmentRate;                                     // 0x0114(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ConversionCD;                                      // 0x0118(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ScopeId;                                           // 0x011C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	bool FindEffectIndex(int32 NumTargets, int32* OutIndex) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101421">();
	}
	static class UConfig_101421* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101421>();
	}
};

// Class Hero_1014.Ability_101421
// 0x00D0 (0x2658 - 0x2588)
class UAbility_101421 : public UMarvelGameplayAbility
{
public:
	bool                                          bInCooling;                                        // 0x2588(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2589[0x7];                                     // 0x2589(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	class UConfig_101421*                         MyConfig;                                          // 0x2590(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSet<TWeakObjectPtr<class AActor>>            ActiveTargets;                                     // 0x2598(0x0050)(Transient, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TMap<TWeakObjectPtr<class AActor>, float>     AccumulativeDamageMap;                             // 0x25E8(0x0050)(Transient, Protected, NativeAccessSpecifierProtected)
	float                                         AccumulativeDamage;                                // 0x2638(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         NumActiveTargets;                                  // 0x263C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2640[0x18];                                    // 0x2640(0x0018)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	int32 GetTraceTargetNumber(TArray<struct FHitResult>* HitResults);
	void OnOwnerApplyDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101421">();
	}
	static class UAbility_101421* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101421>();
	}
};

// Class Hero_1014.Scope_10143301
// 0x0010 (0x1710 - 0x1700)
class AScope_10143301 final : public AMarvelAbilityTargetActor_Scope
{
public:
	class UShapeComponent*                        InvisibleZoneComponent;                            // 0x1700(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsQuoteSourceAdsorbed;                            // 0x1708(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1709[0x7];                                     // 0x1709(0x0007)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Scope_10143301">();
	}
	static class AScope_10143301* GetDefaultObj()
	{
		return GetDefaultObjImpl<AScope_10143301>();
	}
};

// Class Hero_1014.Config_101451
// 0x0030 (0x00C8 - 0x0098)
class UConfig_101451 : public UMarvelAbilityConfig
{
public:
	float                                         MaxLaunchableSlope;                                // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector2D                              ZiplineLengthRange;                                // 0x00A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              HookableSlopeRange;                                // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ElectricRodHeight;                                 // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101451">();
	}
	static class UConfig_101451* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101451>();
	}
};

// Class Hero_1014.Config_101452
// 0x0C20 (0x0CB8 - 0x0098)
class UConfig_101452 final : public UMarvelAbilityConfig
{
public:
	struct FDashAbilityInfo                       DashInfo;                                          // 0x0098(0x0BA8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	float                                         SlideRequireCapsuleHeight;                         // 0x0C40(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SlideRequireCapsuleRadius;                         // 0x0C44(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ZiplineEndReserveLength;                           // 0x0C48(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SlideSpeed;                                        // 0x0C4C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CapsuleHalfHeightWhenSliding;                      // 0x0C50(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CapsuleRadiusWhenSliding;                          // 0x0C54(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AnchorLocationInCharacterSpaceWhenSlidingAnimation; // 0x0C58(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                SlideAnchorOffset;                                 // 0x0C70(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpeedUpWhenDetach;                                 // 0x0C88(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpeedAlongZiplineWhenDetach;                       // 0x0C8C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SweepCapsuleHalfHeightOffset;                      // 0x0C90(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SweepCapsuleRadiusOffset;                          // 0x0C94(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   SlideSocketName;                                   // 0x0C98(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsNeedUserSettingSens;                            // 0x0CA4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CA5[0x3];                                      // 0x0CA5(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	class FName                                   UserSettingSensKey;                                // 0x0CA8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CB4[0x4];                                      // 0x0CB4(0x0004)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101452">();
	}
	static class UConfig_101452* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101452>();
	}
};

// Class Hero_1014.PunisherCableComponent
// 0x0050 (0x0C90 - 0x0C40)
class UPunisherCableComponent final : public UMarvelCableComponent
{
public:
	bool                                          bForceUpdateParticalPosition;                      // 0x0C38(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C39[0x3];                                      // 0x0C39(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         MaxLength;                                         // 0x0C3C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSliding;                                          // 0x0C40(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLaunched;                                         // 0x0C41(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C42[0x6];                                      // 0x0C42(0x0006)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                AnchorLocation;                                    // 0x0C48(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                SlideAnchorOffset;                                 // 0x0C60(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C78[0x18];                                     // 0x0C78(0x0018)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	void ResetParticlesLocationFromStartToEnd();
	void SetAnchorLocation(const struct FVector& InAnchorLocation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherCableComponent">();
	}
	static class UPunisherCableComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPunisherCableComponent>();
	}
};

// Class Hero_1014.PunisherSummonedBase
// 0x0000 (0x08C0 - 0x08C0)
class APunisherSummonedBase : public AMarvelSummonerBase
{
public:
	class UMarvelGameplayAbility* GetOwningAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherSummonedBase">();
	}
	static class APunisherSummonedBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<APunisherSummonedBase>();
	}
};

// Class Hero_1014.Summoned_10145101
// 0x00B0 (0x0970 - 0x08C0)
class ASummoned_10145101 : public APunisherSummonedBase
{
public:
	EZiplineLaunchState                           LaunchState;                                       // 0x08C0(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8C1[0x7];                                      // 0x08C1(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                ZiplineStartLocation;                              // 0x08C8(0x0018)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ZiplineEndLocation;                                // 0x08E0(0x0018)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EZiplineSlideState                            SlideState;                                        // 0x08F8(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsSliding;                                        // 0x08F9(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8FA[0x6];                                      // 0x08FA(0x0006)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                AnchorStartLocation;                               // 0x0900(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AnchorEndLocation;                                 // 0x0918(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AnchorCurrentLocation;                             // 0x0930(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UBoxComponent*                          BoxCollision;                                      // 0x0948(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UBoxComponent*>                  BoxCollisions;                                     // 0x0950(0x0010)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, ContainsInstancedReference, NativeAccessSpecifierPublic)
	int32                                         MaxUseCount;                                       // 0x0960(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurrentUseCount;                                   // 0x0964(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_968[0x8];                                      // 0x0968(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	bool CanSlide();
	void LaunchStateChanged();
	void OnRep_SlideStateChanged();
	void UpdateBoxCollision(bool bEnable, const struct FVector& Start, const struct FVector& End, const struct FPortalSegments& PortalSegments);
	void UpdateSelfLocation();
	void ZiplineEndingChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Summoned_10145101">();
	}
	static class ASummoned_10145101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10145101>();
	}
};

// Class Hero_1014.SummonedMovementComponent_10145101
// 0x01C0 (0x0C00 - 0x0A40)
class USummonedMovementComponent_10145101 final : public USummonedMovementComponent
{
public:
	class UPrimitiveComponent*                    ClawHitComponent;                                  // 0x0A40(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             ClawHitResult;                                     // 0x0A48(0x0170)(Transient, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_BB8[0x48];                                     // 0x0BB8(0x0048)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	void BindClawHitResult(const struct FHitResult& InHitResult);
	void OnClawHitComponentCollisionChanged(class UPrimitiveComponent* InComponent);
	void OnClawPivotDestructibleFracture(class FName BoneName, const struct FVector& ImpactPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SummonedMovementComponent_10145101">();
	}
	static class USummonedMovementComponent_10145101* GetDefaultObj()
	{
		return GetDefaultObjImpl<USummonedMovementComponent_10145101>();
	}
};

// Class Hero_1014.Ability_101451
// 0x0030 (0x25B8 - 0x2588)
class UAbility_101451 : public UMarvelGameplayAbility
{
public:
	struct FVector                                ZiplineStartLocationMeshSpace;                     // 0x2588(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ZiplineStartLocationActorSpace;                    // 0x25A0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	bool CanInstallZipline(const struct FVector& Location, const struct FHitResult& HitResult);
	bool IsValidGroundSetupPoint();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101451">();
	}
	static class UAbility_101451* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101451>();
	}
};

// Class Hero_1014.SummonedCue_10145101_Loop
// 0x0010 (0x0EA0 - 0x0E90)
class ASummonedCue_10145101_Loop : public AMarvelCueNotify_Summoned
{
public:
	class UPunisherCableComponent*                CableComp;                                         // 0x0E90(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASummoned_10145101*                     Zipline;                                           // 0x0E98(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void InitCablePoints();
	void InsertCableParticles();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SummonedCue_10145101_Loop">();
	}
	static class ASummonedCue_10145101_Loop* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummonedCue_10145101_Loop>();
	}
};

// Class Hero_1014.Summoned_10145201
// 0x0040 (0x0900 - 0x08C0)
class ASummoned_10145201 : public APunisherSummonedBase
{
public:
	EZiplineSlideState                            SlideState;                                        // 0x08C0(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EZiplineSlideDirection                        SlideDirection;                                    // 0x08C1(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8C2[0x6];                                      // 0x08C2(0x0006)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                SlideDirectionVector;                              // 0x08C8(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AnchorLocationInCharacterSpaceWhenSlidingAnimation; // 0x08E0(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASummoned_10145101*                     TargetZipline;                                     // 0x08F8(0x0008)(BlueprintVisible, Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void EndSliding();
	void OnRep_SlideDirectionChanged();
	void OnRep_SlideStateChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Summoned_10145201">();
	}
	static class ASummoned_10145201* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10145201>();
	}
};

// Class Hero_1014.Ability_101452
// 0x1158 (0x36E0 - 0x2588)
class UAbility_101452 : public UMarvelGameplayAbility
{
public:
	uint8                                         Pad_2588[0x8];                                     // 0x2588(0x0008)(Fixing Size After Last Property [ Chaos Dumper ])
	class AMarvelBaseCharacter*                   AbilityOwner;                                      // 0x2590(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UConfig_101452*                         Config_101452;                                     // 0x2598(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FMarvelAbilityTraceContext             ZiplineTraceContext;                               // 0x25A0(0x0F90)(BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	class ASummoned_10145201*                     CurrentAnchor;                                     // 0x3530(0x0008)(BlueprintVisible, Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAbilityStage_101452                          AbilityStage;                                      // 0x3538(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3539[0x7];                                     // 0x3539(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                AnchorStartLocation;                               // 0x3540(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASummoned_10145101*                     TargetZipline;                                     // 0x3558(0x0008)(BlueprintVisible, Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             ZiplineTraceResult;                                // 0x3560(0x0170)(BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_36D0[0x10];                                    // 0x36D0(0x0010)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static EZiplineSlideDirection ComputeSlideDirection(const struct FVector& ZiplineSegmentStart, const struct FVector& ZiplineSegmentEnd, const struct FVector& StartPosition, const struct FVector& CameraDirection);

	struct FVector GetDashDirection();
	struct FVector GetTargetLocation();
	bool HasValidZipline(bool bTryTrace);
	void LimitLandingSpeedOnce();
	void OnAbilityStageChanged();
	void OnCharacterMovementUpdated(float DeltaSeconds, const struct FVector& OldLocation, const struct FVector& OldVelocity);
	void OnSummonedRegister(class UMarvelSummonedComponent* SummonedComponent);
	void OnSummonedUnregister(class UMarvelSummonedComponent* SummonedComponent);
	bool TraceForZipline(struct FHitResult* OutHit);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101452">();
	}
	static class UAbility_101452* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101452>();
	}
};

// Class Hero_1014.Cue_Ability_Loop_10145201
// 0x0018 (0x0E68 - 0x0E50)
class ACue_Ability_Loop_10145201 final : public AMarvelCueNotify_Ability
{
public:
	class UNiagaraComponent*                      NS_Smoke;                                          // 0x0E50(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AMarvelBaseCharacter*                   MyCharacter;                                       // 0x0E58(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UMarvelGameplayAbility*                 SourceAbility;                                     // 0x0E60(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Ability_Loop_10145201">();
	}
	static class ACue_Ability_Loop_10145201* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10145201>();
	}
};

// Class Hero_1014.UIController_101452
// 0x0068 (0x0CB8 - 0x0C50)
class UUIController_101452 final : public UUIC_Ability
{
public:
	struct FUIActionData                          ActionData;                                        // 0x0C50(0x0058)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UWidget_AbilityStatusPanel*             AbilityPanel;                                      // 0x0CA8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UWidget_AbilityTarget*                  TargetWidget;                                      // 0x0CB0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UIController_101452">();
	}
	static class UUIController_101452* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIController_101452>();
	}
};

// Class Hero_1014.Config_101461
// 0x0010 (0x11A0 - 0x1190)
class UConfig_101461 : public UConfig_113
{
public:
	float                                         PrinterLiftTime;                                   // 0x1190(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1194[0xC];                                     // 0x1194(0x000C)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101461">();
	}
	static class UConfig_101461* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101461>();
	}
};

// Class Hero_1014.Summoned_10146101
// 0x0210 (0x0AD0 - 0x08C0)
class ASummoned_10146101 : public AMarvelSummonerBase
{
public:
	uint8                                         Pad_8C0[0x18];                                     // 0x08C0(0x0018)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         DefaultRaduis;                                     // 0x08D8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DefaultHalfHeight;                                 // 0x08DC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RadiusInTurret;                                    // 0x08E0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HalfHeightInTurret;                                // 0x08E4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                PlayerMeshOffset;                                  // 0x08E8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                PlayerCapsuleOffset;                               // 0x0900(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PitchScale;                                        // 0x0918(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         YawScale;                                          // 0x091C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxPitch;                                          // 0x0920(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinPitch;                                          // 0x0924(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         YawLerpAlpha;                                      // 0x0928(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PitchLerpAlpha;                                    // 0x092C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BlendInTime;                                       // 0x0930(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BlendOutTime;                                      // 0x0934(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CharacterDistance;                                 // 0x0938(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_93C[0x4];                                      // 0x093C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	TArray<int32>                                 ModeIndexes;                                       // 0x0940(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	bool                                          bAttachToTurret;                                   // 0x0950(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_951[0x7];                                      // 0x0951(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	TMulticastInlineDelegate<void()>              OnNotEnoughAmmoDispatcher;                         // 0x0958(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(ERotateAudioControl RotateAudioControl)> TurretRotateAudioDispatcher;                       // 0x0968(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnTurretDeath;                                     // 0x0978(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnTurretAmmoChanged;                               // 0x0988(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnTurretGetOutComplete;                            // 0x0998(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	bool                                          bIsRotating;                                       // 0x09A8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasResetAudioTimer;                               // 0x09A9(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9AA[0x2];                                      // 0x09AA(0x0002)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         MinPlayRotateAudioDegree;                          // 0x09AC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERotateAudioControl                           RotateAudioControl;                                // 0x09B0(0x0001)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9B1[0x3];                                      // 0x09B1(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         PlayRotateLoopAudioDelay;                          // 0x09B4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StopRotateLoopAudioDelay;                          // 0x09B8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9BC[0x4];                                      // 0x09BC(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	TMulticastInlineDelegate<void(bool Value)>    UpdateMeshDispatcher;                              // 0x09C0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UCapsuleComponent*                      CapsuleComp;                                       // 0x09D0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneComponent*                        PitchRotateComp;                                   // 0x09D8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneComponent*                        YawRotateComp;                                     // 0x09E0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USpringArmComponent*                    SpringArmComp;                                     // 0x09E8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCameraComponent*                       CameraComp;                                        // 0x09F0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCapsuleComponent*                      BaseCapsule1;                                      // 0x09F8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCapsuleComponent*                      BaseCapsule2;                                      // 0x0A00(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEquipComponent*                        EquipComponent;                                    // 0x0A08(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelCrosshairComponent*              CrosshairComponent;                                // 0x0A10(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APlayerController*                      PlayerController;                                  // 0x0A18(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AMarvelAIControllerBase*                MarvelAIController;                                // 0x0A20(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsUsing;                                          // 0x0A28(0x0001)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsGetIn;                                          // 0x0A29(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsGetOut;                                         // 0x0A2A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A2B[0x1D];                                     // 0x0A2B(0x001D)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         CacheCameraYaw;                                    // 0x0A48(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         CacheCameraPitch;                                  // 0x0A4C(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         CacheTurretYaw;                                    // 0x0A50(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_A54[0x74];                                     // 0x0A54(0x0074)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FStencilModifier_DisableDitheringTransparent DisableDitheringTransparent;                       // 0x0AC8(0x0008)(NoDestructor, Protected, NativeAccessSpecifierProtected)

public:
	class UGameplayAbility* GetOwningAbility();
	struct FTransform GetPlayerMeshTransformInTurret();
	struct FTransform GetPlayerTransformInTurret();
	void K2_OnBeginAgentTask();
	void K2_OnEndAgentTask();
	void ManualEndAgentTask();
	void OnCameraBlendComplete();
	void OnPunisherMovementPreUpdate(float DeltaSeconds);
	void OnRep_IsUsing();
	void OnRep_RotateAudioControl();
	void OnSkinInitialized(int32 SkinID);
	void OnViewTargetChange(class AActor* ViewingTarget);
	void PlayRotateLoopAudio();
	void ServerCameraBlendInComplete();
	void SetUsingTurret(bool bInIsUsing);
	void StopRotateLoopAudio();
	void TriggerLookUp(float Val);
	void TriggerTurn(float Val);
	void TriggerTurnAndLookUp(float Turn, float LookUp);
	void UpdatePunisherState();
	void UpdateTurretRotation();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Summoned_10146101">();
	}
	static class ASummoned_10146101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10146101>();
	}
};

// Class Hero_1014.SummonedComp_10146101
// 0x0000 (0x0CA0 - 0x0CA0)
class USummonedComp_10146101 final : public UMarvelSummonedComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SummonedComp_10146101">();
	}
	static class USummonedComp_10146101* GetDefaultObj()
	{
		return GetDefaultObjImpl<USummonedComp_10146101>();
	}
};

// Class Hero_1014.Cue_Ability_Loop_10146101
// 0x0010 (0x0E60 - 0x0E50)
class ACue_Ability_Loop_10146101 final : public AMarvelCueNotify_Ability
{
public:
	class UProjectileMovementComponent*           ProjectileMovementComponent;                       // 0x0E50(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E58[0x8];                                      // 0x0E58(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Ability_Loop_10146101">();
	}
	static class ACue_Ability_Loop_10146101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10146101>();
	}
};

// Class Hero_1014.Weapon_101406
// 0x0000 (0x0C80 - 0x0C80)
class AWeapon_101406 : public AShootingWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Weapon_101406">();
	}
	static class AWeapon_101406* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_101406>();
	}
};

// Class Hero_1014.Turret3PAnimInstance
// 0x0050 (0x0480 - 0x0430)
class UTurret3PAnimInstance final : public UAnimInstance
{
public:
	bool                                          bIsFiring;                                         // 0x0428(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsUsing;                                          // 0x0429(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bNotFoundCamera;                                   // 0x042A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsGetIn;                                          // 0x042B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsGetOut;                                         // 0x042C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_42D[0x3];                                      // 0x042D(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FRotator                               Pitch;                                             // 0x0430(0x0018)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FRotator                               Yaw;                                               // 0x0448(0x0018)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FRotator                               TurretYaw;                                         // 0x0460(0x0018)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_478[0x8];                                      // 0x0478(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	void AnimNotify_LeaveGetInState();
	void AnimNotify_LeaveGetOutState();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Turret3PAnimInstance">();
	}
	static class UTurret3PAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTurret3PAnimInstance>();
	}
};

// Class Hero_1014.Turret1PAnimInstance
// 0x0050 (0x0480 - 0x0430)
class UTurret1PAnimInstance final : public UAnimInstance
{
public:
	bool                                          bIsFiring;                                         // 0x0428(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsUsing;                                          // 0x0429(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bNotFoundCamera;                                   // 0x042A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_42B[0x5];                                      // 0x042B(0x0005)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FRotator                               Pitch;                                             // 0x0430(0x0018)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FRotator                               Yaw;                                               // 0x0448(0x0018)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FRotator                               TurretYaw;                                         // 0x0460(0x0018)(Edit, BlueprintVisible, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_478[0x8];                                      // 0x0478(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Turret1PAnimInstance">();
	}
	static class UTurret1PAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTurret1PAnimInstance>();
	}
};

// Class Hero_1014.PunisherAnimInstance
// 0x01D0 (0x0AE0 - 0x0910)
class UPunisherAnimInstance final : public UMarvelAnimInstance
{
public:
	float                                         ShotgunAddictiveAlpha;                             // 0x0910(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MontageBlendAlpha;                                 // 0x0914(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<struct FPersonalityStruct>             PersonalityStructs;                                // 0x0918(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FMarvelHitAnimConfig                   HitAnimConfigOnTurret;                             // 0x0928(0x002C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, Protected, NativeAccessSpecifierProtected)
	class FName                                   IgnoreLeftClavicleAOCurveName;                     // 0x0954(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bUsingTurret;                                      // 0x0960(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bTurretIsFiring;                                   // 0x0961(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bUsingGatling;                                     // 0x0962(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsUsingWeaponAndBattling;                         // 0x0963(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bLeftHandIKEnabledAndNotAbility;                   // 0x0964(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_965[0x3];                                      // 0x0965(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	int32                                         AimOffsetAnimIndex;                                // 0x0968(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         IgnoreLeftClavicleAOCurveValue;                    // 0x096C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bDirectUseGroundPose;                              // 0x0970(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_971[0x27];                                     // 0x0971(0x0027)(Fixing Size After Last Property [ Chaos Dumper ])
	class APunisherCharacter*                     PunisherCharacter;                                 // 0x0998(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector                                TurretLeftHandLocation;                            // 0x09A0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector                                TurretRightHandLocation;                           // 0x09B8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector                                TurretLeftFootLocation;                            // 0x09D0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector                                TurretRightFootLocation;                           // 0x09E8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FTransform                             GunMuzzleOffset;                                   // 0x0A00(0x0060)(Edit, BlueprintVisible, BlueprintReadOnly, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FTransform                             LeftHandIK;                                        // 0x0A60(0x0060)(Edit, BlueprintVisible, BlueprintReadOnly, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnableAnimIK;                                     // 0x0AC0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bAutonomousProxy;                                  // 0x0AC1(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnableLeftOrRightHandIK;                          // 0x0AC2(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_AC3[0x5];                                      // 0x0AC3(0x0005)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                AimTargetLocation;                                 // 0x0AC8(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnCharacterTagUpdate(const struct FGameplayTag& Tag, bool bTagExists);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherAnimInstance">();
	}
	static class UPunisherAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPunisherAnimInstance>();
	}
};

// Class Hero_1014.PunisherChildActor
// 0x0028 (0x0A88 - 0x0A60)
class APunisherChildActor : public AMarvelCharacterChildActor
{
public:
	struct FGameplayTag                           ShowGatlingTag;                                    // 0x0A60(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A6C[0x4];                                      // 0x0A6C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	class USkeletalMeshComponent*                 Mesh1P;                                            // 0x0A70(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USkeletalMeshComponent*                 DaggerMesh;                                        // 0x0A78(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShowMesh1P;                                       // 0x0A80(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_A81[0x7];                                      // 0x0A81(0x0007)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	void ChangeMeshTo1P();
	void ChangeMeshTo3P();
	bool GetMesh1PState();
	void SetMesh1PState(bool ShowMesh1P);
	void UpdateGatlingState();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherChildActor">();
	}
	static class APunisherChildActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APunisherChildActor>();
	}
};

// Class Hero_1014.PunisherCharacter
// 0x0050 (0x18C0 - 0x1870)
class APunisherCharacter : public AMarvelBaseCharacter
{
public:
	struct FVector                                EffectorLocation_Riffle;                           // 0x1868(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                EffectorLocation_Shotgun;                          // 0x1880(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTurretIsFiring;                                   // 0x1898(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUsingTurret;                                      // 0x1899(0x0001)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_189A[0x6];                                     // 0x189A(0x0006)(Fixing Size After Last Property [ Chaos Dumper ])
	class ASummoned_10146101*                     TurretActor;                                       // 0x18A0(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPunisherMoveLogicBaseComponent*        PunisherMoveLogic;                                 // 0x18A8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsUsingGatling;                                   // 0x18B0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_18B1[0x3];                                     // 0x18B1(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	int32                                         GatlingIdleIdx;                                    // 0x18B4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_18B8[0x8];                                     // 0x18B8(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])

public:
	bool IsUsingGatling();
	void OnRep_IsUsingGatling();
	void SetGatlingGunUsing(bool bIsUsing);
	void SetGatlingMaterialVisible(bool bVisible);
	void SetTurretActor(class ASummoned_10146101* Turret);
	void SetTurretFiringState(bool bIsFiring);
	void SetUsingTurretState(bool bIsUsing);

	class USkeletalMeshComponent* GetMesh1P() const;
	class ASummoned_10146101* GetTurret() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherCharacter">();
	}
	static class APunisherCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APunisherCharacter>();
	}
};

// Class Hero_1014.PunisherAudioComponent
// 0x0000 (0x0C80 - 0x0C80)
class UPunisherAudioComponent final : public UCharacterAudioComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherAudioComponent">();
	}
	static class UPunisherAudioComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPunisherAudioComponent>();
	}
};

// Class Hero_1014.PunisherMoveLogicBaseComponent
// 0x0000 (0x03F0 - 0x03F0)
class UPunisherMoveLogicBaseComponent final : public UMarvelMoveLogicBaseComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherMoveLogicBaseComponent">();
	}
	static class UPunisherMoveLogicBaseComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPunisherMoveLogicBaseComponent>();
	}
};

// Class Hero_1014.PunisherMovementComponent
// 0x0000 (0x1B80 - 0x1B80)
class UPunisherMovementComponent final : public UMarvelCharacterMovementComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PunisherMovementComponent">();
	}
	static class UPunisherMovementComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPunisherMovementComponent>();
	}
};

// Class Hero_1014.TabData_1014
// 0x0000 (0x0050 - 0x0050)
class UTabData_1014 final : public UHeroTabDataBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TabData_1014">();
	}
	static class UTabData_1014* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTabData_1014>();
	}
};

}

