#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Hero_1045

#include "Basic.hpp"


namespace SDK
{

// Enum Hero_1045.EOctopusState
// NumValues: 0x0004
enum class EOctopusState : uint8
{
	Idle                                     = 0,
	NormalAttacking                          = 1,
	EnhancedAttacking                        = 2,
	EOctopusState_MAX                        = 3,
};

}

