#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Hero_1051

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function Hero_1051.Ability_105141.GetPortalFromHitResult
// 0x0178 (0x0178 - 0x0000)
struct Ability_105141_GetPortalFromHitResult final
{
public:
	struct FHitResult                             HitResult;                                         // 0x0000(0x0170)(Parm, ContainsInstancedReference, NativeAccessSpecifierPublic)
	class AActor*                                 ReturnValue;                                       // 0x0170(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1051.Ability_105141.OnTargetActorChangedByPortal
// 0x0008 (0x0008 - 0x0000)
struct Ability_105141_OnTargetActorChangedByPortal final
{
public:
	class APortalViewActor*                       InPortal;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1051.Ability_105141.SetInitVelocity
// 0x0030 (0x0030 - 0x0000)
struct Ability_105141_SetInitVelocity final
{
public:
	struct FVector                                ClientJumpEndPoint;                                // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ClientMiddlePoint;                                 // 0x0018(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1051.Ability_105141.SetupStartVelocity
// 0x0020 (0x0020 - 0x0000)
struct Ability_105141_SetupStartVelocity final
{
public:
	struct FVector                                TargetVelocity;                                    // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxSpeed;                                          // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Chaos Dumper ])
};

// Function Hero_1051.TraceComponent_10515101.DoTrace
// 0x0010 (0x0010 - 0x0000)
struct TraceComponent_10515101_DoTrace final
{
public:
	TArray<struct FVector>                        ValidPoints;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};

// Function Hero_1051.Ability_105151.GetPointRotation
// 0x00A0 (0x00A0 - 0x0000)
struct Ability_105151_GetPointRotation final
{
public:
	struct FVector                                InNormal;                                          // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FTransform                             StandardTransform;                                 // 0x0020(0x0060)(Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               ReturnValue;                                       // 0x0080(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_98[0x8];                                       // 0x0098(0x0008)(Fixing Struct Size After Last Property [ Chaos Dumper ])
};

// Function Hero_1051.Ability_105162.SwitchTimelineTask
// 0x000C (0x000C - 0x0000)
struct Ability_105162_SwitchTimelineTask final
{
public:
	class FName                                   SectionName;                                       // 0x0000(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1051.BenjaminGrimAnimInstance.GetSynergyRideAnimation
// 0x0010 (0x0010 - 0x0000)
struct BenjaminGrimAnimInstance_GetSynergyRideAnimation final
{
public:
	struct FAnimUpdateContext                     PoseContext;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Hero_1051.BenjaminGrimAnimInstance.GetSynergyRideStartAnimation
// 0x0010 (0x0010 - 0x0000)
struct BenjaminGrimAnimInstance_GetSynergyRideStartAnimation final
{
public:
	struct FAnimUpdateContext                     PoseContext;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Hero_1051.BenjaminGrimAnimInstance.OnTagUpdated
// 0x0010 (0x0010 - 0x0000)
struct BenjaminGrimAnimInstance_OnTagUpdated final
{
public:
	struct FGameplayTag                           TagUpdated;                                        // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          TagExists;                                         // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Chaos Dumper ])
};

// Function Hero_1051.BenjaminGrimAnimInstance.UpdateSynergyRideStartNode
// 0x0020 (0x0020 - 0x0000)
struct BenjaminGrimAnimInstance_UpdateSynergyRideStartNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1051.BanjaminAnimInstance_105161.OnGroundDetailPostBecomeRelevant
// 0x0020 (0x0020 - 0x0000)
struct BanjaminAnimInstance_105161_OnGroundDetailPostBecomeRelevant final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1051.BanjaminAnimInstance_105161.OnReleantSynergyRideNode
// 0x0020 (0x0020 - 0x0000)
struct BanjaminAnimInstance_105161_OnReleantSynergyRideNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1051.BenjaminGrimCharacter.SetSynergyExtraCapsuleComponentEnabled
// 0x0001 (0x0001 - 0x0000)
struct BenjaminGrimCharacter_SetSynergyExtraCapsuleComponentEnabled final
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

