#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: HighLightData_1034_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HighLightData_1034_BP.HighLightData_1034_BP_C
// 0x0000 (0x00B0 - 0x00B0)
class UHighLightData_1034_BP_C final : public UHighLightData_1034
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HighLightData_1034_BP_C">();
	}
	static class UHighLightData_1034_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighLightData_1034_BP_C>();
	}
};

}

