#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_102974

#include "Basic.hpp"

#include "PyAbility_102972_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_102974.KnockUp_102974_C
// 0x0000 (0x1DB0 - 0x1DB0)
class UKnockUp_102974_C final : public UPyKnockUp_102972
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_102974_C">();
	}
	static class UKnockUp_102974_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_102974_C>();
	}
};

}

