#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_10428102

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_10428102.KnockUp_10428102_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_10428102_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_10428102_C">();
	}
	static class UKnockUp_10428102_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_10428102_C>();
	}
};

}

