#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_102171_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_102171_BP.KnockUp_102171_BP_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_102171_BP_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_102171_BP_C">();
	}
	static class UKnockUp_102171_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_102171_BP_C>();
	}
};

}

