#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_10427101

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_10427101.KnockUp_10427101_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_10427101_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_10427101_C">();
	}
	static class UKnockUp_10427101_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_10427101_C>();
	}
};

}

