#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_102241

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_102241.KnockUp_102241_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_102241_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_102241_C">();
	}
	static class UKnockUp_102241_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_102241_C>();
	}
};

}

