#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_10369201

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_10369201.KnockUp_10369201_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_10369201_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_10369201_C">();
	}
	static class UKnockUp_10369201_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_10369201_C>();
	}
};

}

