#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_105151

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_105151.KnockUp_105151_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_105151_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_105151_C">();
	}
	static class UKnockUp_105151_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_105151_C>();
	}
};

}

