#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: KnockUp_104041

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_104041.KnockUp_104041_C
// 0x0000 (0x1DA8 - 0x1DA8)
class UKnockUp_104041_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_104041_C">();
	}
	static class UKnockUp_104041_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_104041_C>();
	}
};

}

