#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: LevelScopeCheckComponentBP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LevelScopeCheckComponentBP.LevelScopeCheckComponentBP_C
// 0x0000 (0x0E20 - 0x0E20)
class ULevelScopeCheckComponentBP_C final : public ULevelScopeCheckComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LevelScopeCheckComponentBP_C">();
	}
	static class ULevelScopeCheckComponentBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULevelScopeCheckComponentBP_C>();
	}
};

}

