#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: LS_HoverToFull

#include "Basic.hpp"


namespace SDK::Params
{

// Function LS_HoverToFull.LS_HoverToFull_DirectorBP_C.ExecuteUbergraph_LS_HoverToFull_DirectorBP
// 0x0004 (0x0004 - 0x0000)
struct LS_HoverToFull_DirectorBP_C_ExecuteUbergraph_LS_HoverToFull_DirectorBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

