#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: MarvelCameraComponentBP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MarvelCameraComponentBP.MarvelCameraComponentBP_C
// 0x0000 (0x0EA0 - 0x0EA0)
class UMarvelCameraComponentBP_C final : public UMarvelCameraComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MarvelCameraComponentBP_C">();
	}
	static class UMarvelCameraComponentBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMarvelCameraComponentBP_C>();
	}
};

}

