#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: MarvelActivityRow117_BP

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct MarvelActivityRow117_BP.MarvelActivityRow117_BP
// 0x0004 (0x0004 - 0x0000)
struct FMarvelActivityRow117_BP final
{
public:
	int32                                         battle_count_16_FE729C9A4ABC3CA8225BF49872BD3D71;  // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

