#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: MarvelMatchGameMapTable

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct MarvelMatchGameMapTable.MarvelMatchGameMapTable
// 0x0020 (0x0020 - 0x0000)
struct FMarvelMatchGameMapTable final
{
public:
	bool                                          Delivery_8_E0EB8BBE4C7589DBC353009EAD313FCF;       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	int32                                         ModeId_2_3EB7211E45982A9C77A2A28B7EF0267D;         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   PlayModeName_6_063376B74B59BF66B375B0AA7EF5CFEA;   // 0x0008(0x0018)(Edit, BlueprintVisible)
};

}

