#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: MediaPlate

#include "Basic.hpp"


namespace SDK
{

// Enum MediaPlate.EMediaPlateEventState
// NumValues: 0x0008
enum class EMediaPlateEventState : uint8
{
	Play                                     = 0,
	Open                                     = 1,
	Close                                    = 2,
	Pause                                    = 3,
	Reverse                                  = 4,
	Forward                                  = 5,
	Rewind                                   = 6,
	MAX                                      = 7,
};

}

