#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: MosClient_Activity112

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// PythonClass MosClient_Activity112.Spring_Activity_Award_Data
// 0x0000 (0x0030 - 0x0030)
class USpring_Activity_Award_Data final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Spring_Activity_Award_Data">();
	}
	static class USpring_Activity_Award_Data* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpring_Activity_Award_Data>();
	}
};

}

