#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Nine999_CharacterBP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 9999_CharacterBP.9999_CharacterBP_C
// 0x0000 (0x1870 - 0x1870)
class ANine999_CharacterBP_C final : public AMarvelBaseCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"9999_CharacterBP_C">();
	}
	static class ANine999_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANine999_CharacterBP_C>();
	}
};

}

