#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: NotTreatShield_10365101

#include "Basic.hpp"

#include "Ability_NotTreatFall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NotTreatShield_10365101.NotTreatShield_10365101_C
// 0x0000 (0x12C8 - 0x12C8)
class UNotTreatShield_10365101_C final : public UAbility_NotTreatFall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NotTreatShield_10365101_C">();
	}
	static class UNotTreatShield_10365101_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNotTreatShield_10365101_C>();
	}
};

}

