#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: NotTreatShield_10523101_BP

#include "Basic.hpp"

#include "Ability_NotTreatImmunityBlockFall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NotTreatShield_10523101_BP.NotTreatShield_10523101_BP_C
// 0x0000 (0x1330 - 0x1330)
class UNotTreatShield_10523101_BP_C final : public UAbility_NotTreatImmunityBlockFall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NotTreatShield_10523101_BP_C">();
	}
	static class UNotTreatShield_10523101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNotTreatShield_10523101_BP_C>();
	}
};

}

