#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: One043_CharacterBP

#include "Basic.hpp"

#include "PyStarlordCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 1043_CharacterBP.1043_CharacterBP_C
// 0x0000 (0x18C0 - 0x18C0)
class AOne043_CharacterBP_C final : public APyStarlordCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1043_CharacterBP_C">();
	}
	static class AOne043_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOne043_CharacterBP_C>();
	}
};

}

