#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: One05051_KeepMoveTo_AddMoveInput_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 105051_KeepMoveTo_AddMoveInput_BP.105051_KeepMoveTo_AddMoveInput_BP_C
// 0x0000 (0x1138 - 0x1138)
class UOne05051_KeepMoveTo_AddMoveInput_BP_C final : public UAbility_136_AddMovementInput
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"105051_KeepMoveTo_AddMoveInput_BP_C">();
	}
	static class UOne05051_KeepMoveTo_AddMoveInput_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOne05051_KeepMoveTo_AddMoveInput_BP_C>();
	}
};

}

