#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: One045_CharacterBP

#include "Basic.hpp"

#include "PyNamorCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 1045_CharacterBP.1045_CharacterBP_C
// 0x0000 (0x18A0 - 0x18A0)
class AOne045_CharacterBP_C final : public APyNamorCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1045_CharacterBP_C">();
	}
	static class AOne045_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOne045_CharacterBP_C>();
	}
};

}

