#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: One029001_ShowAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyShowAnimInstance_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass 1029001_ShowAnimBP.1029001_ShowAnimBP_C
// 0x0130 (0x0690 - 0x0560)
class UOne029001_ShowAnimBP_C final : public UPyShowAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0560(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Tag;                        // 0x0568(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0570(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0578(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0580(0x0038)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x05B8(0x00D0)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_1029001_ShowAnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1029001_ShowAnimBP_C">();
	}
	static class UOne029001_ShowAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOne029001_ShowAnimBP_C>();
	}
};

}

