#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: OptimusSettings

#include "Basic.hpp"

#include "OptimusSettings_structs.hpp"
#include "DeveloperSettings_classes.hpp"


namespace SDK
{

// Class OptimusSettings.OptimusSettings
// 0x0068 (0x00B0 - 0x0048)
class UOptimusSettings final : public UDeveloperSettings
{
public:
	EOptimusDefaultDeformerMode                   DefaultMode;                                       // 0x0048(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	TSoftObjectPtr<class UMeshDeformer>           DefaultDeformer;                                   // 0x0050(0x0030)(Edit, Config, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UMeshDeformer>           DefaultRecomputeTangentDeformer;                   // 0x0080(0x0030)(Edit, Config, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"OptimusSettings">();
	}
	static class UOptimusSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOptimusSettings>();
	}
};

}

