#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Projectile_10246101_BP

#include "Basic.hpp"

#include "PyAbility_102461_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_10246101_BP.Projectile_10246101_BP_C
// 0x0000 (0x3120 - 0x3120)
class AProjectile_10246101_BP_C final : public APyProjectile_102461
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_10246101_BP_C">();
	}
	static class AProjectile_10246101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10246101_BP_C>();
	}
};

}

