#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Projectile_10503101_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Marvel_structs.hpp"
#include "PyAbility_105031_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_10503101_BP.Projectile_10503101_BP_C
// 0x03A0 (0x34B0 - 0x3110)
class AProjectile_10503101_BP_C final : public APyProjectile_10503101
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x3110(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FMarvelTraceRule                       Trace_Rule;                                        // 0x3118(0x0390)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Projectile_10503101_BP(int32 EntryPoint);
	void K2_OnPenetrate(const struct FHitResult& ImpactResult, const struct FVector& ImpactVelocity);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_10503101_BP_C">();
	}
	static class AProjectile_10503101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10503101_BP_C>();
	}
};

}

