#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_102981

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102981.PyAbility_102981
// 0x0000 (0x2840 - 0x2840)
class UPyAbility_102981 : public UAbility_109
{
public:
	void BeginPlay();
	void EndPlay();
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void ChangeSculpt();
	void OnDurationEnd();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_102981">();
	}
	static class UPyAbility_102981* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102981>();
	}
};

}

