#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbilityScaleGravity

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbilityScaleGravity.PyAbilityScaleGravity
// 0x0000 (0x1100 - 0x1100)
class UPyAbilityScaleGravity final : public UMarvelEffectGameplayAbility
{
public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool Cancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbilityScaleGravity">();
	}
	static class UPyAbilityScaleGravity* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbilityScaleGravity>();
	}
};

}

