#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_103343

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_103343.PyAbility_103343.OnForwardPressed
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_103343_OnForwardPressed final
{
public:
	float                                         StateIntervalTime;                                 // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

