#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_103419

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103419.PyAbility_103419
// 0x0000 (0x2590 - 0x2590)
class UPyAbility_103419 : public UAbility_108
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103419">();
	}
	static class UPyAbility_103419* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103419>();
	}
};

}

