#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_104981

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Hero_1049_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104981.PyConfig_104981
// 0x2AB8 (0x2B50 - 0x0098)
class UPyConfig_104981 final : public UMarvelAbilityConfig
{
public:
	float                                         JumpVelocity;                                      // 0x0098(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FDashAbilityInfo                       RaiseDashInfo;                                     // 0x00A0(0x0BA8)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	int32                                         HoverBuffID;                                       // 0x0C48(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C4C[0x4];                                      // 0x0C4C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	TArray<int32>                                 BuffIds;                                           // 0x0C50(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FFindGroundParam                       TraceParam;                                        // 0x0C60(0x0FD0)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FGameplayTag                           TraceCueTag;                                       // 0x1C30(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C3C[0x4];                                     // 0x1C3C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FDashAbilityInfo                       DashInfo;                                          // 0x1C40(0x0BA8)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	int32                                         DashScopeID;                                       // 0x27E8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GrabBuffID;                                        // 0x27EC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GrabBuffID_CollideKnockDown;                       // 0x27F0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           GrabCollideTag;                                    // 0x27F4(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTagRequirements               CollideKnockTagRequire;                            // 0x2800(0x0118)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FMarvelApplyPinnedMotionConfig         PinnedConfig;                                      // 0x2918(0x0230)(Edit, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_104981">();
	}
	static class UPyConfig_104981* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104981>();
	}
};

// PythonClass PyAbility_104981.PyAbility_104981
// 0x0020 (0x25C0 - 0x25A0)
class UPyAbility_104981 : public UAbility_104981
{
public:
	TMulticastInlineDelegate<void()>              OnPawnFloatStart;                                  // 0x25A0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPawnFloatEnd;                                    // 0x25B0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	float GetAbilityDuration();
	void K2_ActivateAbility();
	void MissileEventNotify();
	void BreakEventNotify();
	void OnRaiseDashFinish(EDashStopReason Reason);
	void OnReachedJumpApex();
	void OnSelectConfirm(const struct FGameplayAbilityTargetDataHandle& Data);
	void OnTraceResults(const TArray<struct FHitResult>& HitResults);
	struct FGameplayTagRequirements GetCollideKnockDownRequire();
	void OnDashFinish(EDashStopReason Reason);
	void OnHoverBuffRemove(const struct FGameplayEffectRemovalInfo& InGameplayEffectRemovalInfo);
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_104981">();
	}
	static class UPyAbility_104981* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104981>();
	}
};

// PythonClass PyAbility_104981.PyAbility_AirGrab_104981
// 0x0000 (0x1170 - 0x1170)
class UPyAbility_AirGrab_104981 final : public UAbility_AirGrab
{
public:
	void OnActiveAbility();
	bool K2_ShouldSkipInstigatorHit(class AActor* SelfActor, const struct FHitResult& InHit);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_AirGrab_104981">();
	}
	static class UPyAbility_AirGrab_104981* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_AirGrab_104981>();
	}
};

}

