#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_104001

#include "Basic.hpp"

#include "Hero_1040_classes.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104001.PyUIController_104001
// 0x0000 (0x0C50 - 0x0C50)
class UPyUIController_104001 final : public UUIC_Ability
{
public:
	void OnInit();
	void OnDestruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_104001">();
	}
	static class UPyUIController_104001* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_104001>();
	}
};

// PythonClass PyAbility_104001.PyConfig_104001
// 0x0000 (0x0108 - 0x0108)
class UPyConfig_104001 final : public UConfig_104001
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_104001">();
	}
	static class UPyConfig_104001* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104001>();
	}
};

// PythonClass PyAbility_104001.PyCue_Buff_Loop_10400103
// 0x0000 (0x1038 - 0x1038)
class APyCue_Buff_Loop_10400103 final : public AMarvelCueNotify_Buff
{
public:
	void WhileActiveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Buff_Loop_10400103">();
	}
	static class APyCue_Buff_Loop_10400103* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_Loop_10400103>();
	}
};

// PythonClass PyAbility_104001.PyAbility_104001
// 0x0000 (0x2598 - 0x2598)
class UPyAbility_104001 : public UAbility_104001
{
public:
	void K2_ActivateAbility();
	void OnTagUpdate(const struct FGameplayTag& Tag, bool Exist);
	void OnOwnerDeath(class AActor* InSource, class AActor* InTarget, const struct FAttributeModifierHandle& ParamHandle);
	void OnDurationEnd();
	bool CanActivate();
	void PreMissileEventNotify();
	void MissileEventNotify();
	void BreakEventNotify();
	void K2_OnEndAbility(bool bWasCancelled);
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageBlendOut(const class FString& Tag);
	void NativeOnMontageInterrupted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);
	void NativeOnMontageEvent(const class FString& Tag);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_104001">();
	}
	static class UPyAbility_104001* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104001>();
	}
};

}

