#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_103342

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103342.PyEffectAbility_GravityChange_103342
// 0x0010 (0x1110 - 0x1100)
class UPyEffectAbility_GravityChange_103342 : public UMarvelEffectGameplayAbility
{
public:
	class UCurveFloat*                            GravityScaleCurve;                                 // 0x1100(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Debug;                                             // 0x1108(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();
	void ReceiveTick(float DeltaTime);
	void OnLanded(const struct FHitResult& Hit);
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyEffectAbility_GravityChange_103342">();
	}
	static class UPyEffectAbility_GravityChange_103342* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyEffectAbility_GravityChange_103342>();
	}
};

}

