#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_105211

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_105211.PyAbility_105211
// 0x0000 (0x2680 - 0x2680)
class UPyAbility_105211 : public UMarvelAbility_DoubleJump
{
public:
	void BeginPlay();
	void K2_ActivateAbility();
	bool CanActivate();
	void K2_OnLaunchCharacter(const struct FVector2D& Direction);
	void BreakEventNotify();
	void DoubleJump_Internal();
	void K2_OnEndAbility(bool bWasCancelled);
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageInterrupted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_105211">();
	}
	static class UPyAbility_105211* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_105211>();
	}
};

// PythonClass PyAbility_105211.PyUIController_105211
// 0x0000 (0x0C50 - 0x0C50)
class UPyUIController_105211 final : public UUIC_Ability
{
public:
	void SetAbility(int32 InAbilityId, class UGameplayAbility* InAbility);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_105211">();
	}
	static class UPyUIController_105211* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_105211>();
	}
};

}

