#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_103304

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103304.PyConfig_103304
// 0x0008 (0x00A0 - 0x0098)
class UPyConfig_103304 final : public UMarvelAbilityConfig
{
public:
	bool                                          AutoPullBullet;                                    // 0x0098(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_103304">();
	}
	static class UPyConfig_103304* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_103304>();
	}
};

// PythonClass PyAbility_103304.PyAbility_103304
// 0x0000 (0x2590 - 0x2590)
class UPyAbility_103304 : public UAbility_108
{
public:
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103304">();
	}
	static class UPyAbility_103304* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103304>();
	}
};

}

