#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAbility_103862

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103862.PyAbility_103862
// 0x0000 (0x25C0 - 0x25C0)
class UPyAbility_103862 : public UAbility_112
{
public:
	void BeginPlay();
	void K2_ActivateAbility();
	int32 GetCurrentTimelineIndex();
	void TryThrow();
	void OnProjectileSpawnSuccess(class AActor* SpawnActor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103862">();
	}
	static class UPyAbility_103862* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103862>();
	}
};

}

