#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyActorEventPoint

#include "Basic.hpp"

#include "PyActorEventPoint_classes.hpp"


namespace SDK
{

// PythonFunction PyActorEventPoint.PyActorEventPoint.PyUpdatePosition
// (Native, Public, BlueprintCallable)

void APyActorEventPoint::PyUpdatePosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyActorEventPoint", "PyUpdatePosition");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

