#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAccessibilityManager

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAccessibilityManager.PyAccessibilityManager
// 0x0000 (0x0038 - 0x0038)
class UPyAccessibilityManager final : public UMarvelGameInstanceSubsystem
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAccessibilityManager">();
	}
	static class UPyAccessibilityManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAccessibilityManager>();
	}
};

}

