#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAnonymousModeSubsystem

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAnonymousModeSubsystem.PyAnonymousModeSubsystem
// 0x0000 (0x00B8 - 0x00B8)
class UPyAnonymousModeSubsystem final : public UAnonymousModeSubsystem
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAnonymousModeSubsystem">();
	}
	static class UPyAnonymousModeSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAnonymousModeSubsystem>();
	}
};

}

