#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyAssaultRuleComponent

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyAssaultRuleComponent.PyAssaultRuleComponent.ActivationNow
// 0x0008 (0x0008 - 0x0000)
struct PyAssaultRuleComponent_ActivationNow final
{
public:
	class APyObjective*                           Objective;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

