#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyBanPickRuleComponent

#include "Basic.hpp"

#include "python_enums_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyBanPickRuleComponent.PyBanPickRuleComponent.notify_2c_ban_pickstate_time_change
// 0x0008 (0x0008 - 0x0000)
struct PyBanPickRuleComponent_notify_2c_ban_pickstate_time_change final
{
public:
	EBanPickState                                 ban_pick_state;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         total_time;                                        // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

