#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyControlLevelStatistics

#include "Basic.hpp"

#include "PyLevelStatistics_classes.hpp"
#include "Marvel_structs.hpp"


namespace SDK
{

// PythonClass PyControlLevelStatistics.PyControlLevelStatistics
// 0x0000 (0x0038 - 0x0038)
class UPyControlLevelStatistics final : public UPyLevelStatistics
{
public:
	void Initialize();
	void Shutdown();
	void OnRoundFightStart();
	float OnRoundEnd();
	void OnControlOwnerChanged(class AActor* Control, EOwnershipType OwnerSide);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyControlLevelStatistics">();
	}
	static class UPyControlLevelStatistics* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyControlLevelStatistics>();
	}
};

}

