#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyControllerVibrationSubsystem

#include "Basic.hpp"

#include "PyControllerVibrationSubsystem_classes.hpp"


namespace SDK
{

// PythonFunction PyControllerVibrationSubsystem.PyControllerVibrationSubsystem.OnInitialized
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyControllerVibrationSubsystem::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyControllerVibrationSubsystem", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

