#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyCustomColorManager

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyCustomColorManager.PyCustomColorManager
// 0x0000 (0x0160 - 0x0160)
class UPyCustomColorManager final : public UCustomColorManager
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCustomColorManager">();
	}
	static class UPyCustomColorManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyCustomColorManager>();
	}
};

}

