#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyDataAsset_ValentinesDay

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyDataAsset_ValentinesDay.PyDataAsset_ValentinesDay
// 0x0030 (0x0068 - 0x0038)
class UPyDataAsset_ValentinesDay final : public UPrimaryDataAsset
{
public:
	TArray<class FString>                         WomanHeadIcon;                                     // 0x0038(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FString>                         ManHeadIcon;                                       // 0x0048(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FDateTime                              ActivityStartTime;                                 // 0x0058(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              ActivityEndTime;                                   // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyDataAsset_ValentinesDay">();
	}
	static class UPyDataAsset_ValentinesDay* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyDataAsset_ValentinesDay>();
	}
};

}

