#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyLevelGroupMoveComponent

#include "Basic.hpp"

#include "PyLevelGroupMoveComponent_classes.hpp"


namespace SDK
{

// PythonFunction PyLevelGroupMoveComponent.PyLevelGroupMoveComponent.OnSlowMotionStart
// (Native, Public, BlueprintCallable)

void UPyLevelGroupMoveComponent::OnSlowMotionStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelGroupMoveComponent", "OnSlowMotionStart");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyLevelGroupMoveComponent.PyLevelGroupMoveComponent.OnRep_CurProgress
// (Native, Protected, BlueprintCallable)

void UPyLevelGroupMoveComponent::OnRep_CurProgress()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelGroupMoveComponent", "OnRep_CurProgress");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

