#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyLevelNodeEffectComponent

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyLevelNodeEffectComponent.PyLevelNodeEffectComponent.OnViewingTargetChanged
// 0x0008 (0x0008 - 0x0000)
struct PyLevelNodeEffectComponent_OnViewingTargetChanged final
{
public:
	class AActor*                                 InActor;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyLevelNodeEffectComponent.PyLevelNodeEffectComponent.SetViewingCharacter
// 0x0008 (0x0008 - 0x0000)
struct PyLevelNodeEffectComponent_SetViewingCharacter final
{
public:
	class AMarvelBaseCharacter*                   ViewingCharacter;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

