#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyRichTextTimeDecorator

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyRichTextTimeDecorator.PyRichTextTimeDecorator.FormatTimeFromPython
// 0x0020 (0x0020 - 0x0000)
struct PyRichTextTimeDecorator_FormatTimeFromPython final
{
public:
	class FString                                 TimeString;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};

}

