#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyRichTextCustomWidgetDecorator

#include "Basic.hpp"

#include "PyRichTextCustomWidgetDecorator_classes.hpp"
#include "PyRichTextCustomWidgetDecorator_parameters.hpp"


namespace SDK
{

// PythonFunction PyRichTextCustomWidgetDecorator.PyRichTextCustomWidgetDecorator.SetWidgetStyle
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TMap<class FString, class FString>      InMetaData                                             (ConstParm, Parm, OutParm, ReferenceParm)

void UPyRichTextCustomWidgetDecorator::SetWidgetStyle(const class UUserWidget* Widget, const TMap<class FString, class FString>& InMetaData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyRichTextCustomWidgetDecorator", "SetWidgetStyle");

	Params::PyRichTextCustomWidgetDecorator_SetWidgetStyle Parms{};

	Parms.Widget = Widget;
	Parms.InMetaData = std::move(InMetaData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyRichTextCustomWidgetDecorator.PyRichTextCustomWidgetDecorator.SetWidgetData
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FMarvelRichTextBlockCustomWidgetDataData                                                   (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)

void UPyRichTextCustomWidgetDecorator::SetWidgetData(const class UUserWidget* Widget, const struct FMarvelRichTextBlockCustomWidgetData& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyRichTextCustomWidgetDecorator", "SetWidgetData");

	Params::PyRichTextCustomWidgetDecorator_SetWidgetData Parms{};

	Parms.Widget = Widget;
	Parms.Data = std::move(Data);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

