#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyShowAnimInstanceBase

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.BlueprintPreUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct PyShowAnimInstanceBase_BlueprintPreUpdateAnimation final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnPlayShowAnim
// 0x0001 (0x0001 - 0x0000)
struct PyShowAnimInstanceBase_OnPlayShowAnim final
{
public:
	bool                                          IsPlay;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnPlayToggleAnim
// 0x0001 (0x0001 - 0x0000)
struct PyShowAnimInstanceBase_OnPlayToggleAnim final
{
public:
	bool                                          IsToggleHalf_0;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnIsHalfChanged
// 0x0001 (0x0001 - 0x0000)
struct PyShowAnimInstanceBase_OnIsHalfChanged final
{
public:
	bool                                          IsToggleHalf_0;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnPlayEmoteAnim
// 0x0010 (0x0010 - 0x0000)
struct PyShowAnimInstanceBase_OnPlayEmoteAnim final
{
public:
	class FString                                 ItemId;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnPlayHeroGaller_CardPose
// 0x0001 (0x0001 - 0x0000)
struct PyShowAnimInstanceBase_OnPlayHeroGaller_CardPose final
{
public:
	bool                                          IsPlayCardPose_0;                                  // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnPlayHeroGaller_HoverStand
// 0x0001 (0x0001 - 0x0000)
struct PyShowAnimInstanceBase_OnPlayHeroGaller_HoverStand final
{
public:
	bool                                          IsPlayHoverStand_0;                                // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.GetLSHoverStandIsPlaying
// 0x0001 (0x0001 - 0x0000)
struct PyShowAnimInstanceBase_GetLSHoverStandIsPlaying final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnShowActorCameraGaze
// 0x0028 (0x0028 - 0x0000)
struct PyShowAnimInstanceBase_OnShowActorCameraGaze final
{
public:
	bool                                          TurnCameraGaze_0;                                  // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector                                CameraLocation_0;                                  // 0x0008(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OpenBlendTime;                                     // 0x0020(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CloseBlendTime;                                    // 0x0024(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyShowAnimInstanceBase.PyShowAnimInstanceBase.OnPlayVoiceAnim
// 0x0008 (0x0008 - 0x0000)
struct PyShowAnimInstanceBase_OnPlayVoiceAnim final
{
public:
	class UAnimSequence*                          VoiceAnim_0;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

