#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PySignalHandlerActor

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "DeclarativeUnreal_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PySignalHandlerActor.PySignalHandlerActor
// 0x0230 (0x0860 - 0x0630)
class APySignalHandlerActor : public ASignalHandlerActor
{
public:
	struct FSignalResult                          RequestResult;                                     // 0x0630(0x0190)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	bool                                          BeCancelled;                                       // 0x07C0(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7C1[0x3];                                      // 0x07C1(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	int32                                         AbilityID;                                         // 0x07C4(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsFallOff;                                         // 0x07C8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7C9[0x7];                                      // 0x07C9(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FDeclarationHolder                     ViewerSideWatcher;                                 // 0x07D0(0x0010)(NativeAccessSpecifierPublic)
	TMap<struct FGameplayTag, class UNiagaraSystem*> Tag2NiagaraSystem;                                 // 0x07E0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	float                                         CheckViewInterval;                                 // 0x0830(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_834[0x4];                                      // 0x0834(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FVector2D                              SceneScreenOffset;                                 // 0x0838(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ObjectScreenOffset;                                // 0x0848(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          CancelAudioEvent;                                  // 0x0858(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void SetRequestResult(const struct FSignalResult& Result);
	void SetAbilityID(int32 InAbilityId);
	void CancelSignal(bool is_cancel);
	void SetBeCancelled(bool IsBeCancelled);
	void OnRep_BeCancelled();
	void StartHandlerSignal(const struct FSignalResult& Result);
	void EndHandlerSignal(const struct FSignalResult& Result);
	void OnSummonedEndAgentTask(class AActor* InActor);
	void OnComOwnerChanged(class AActor* InActor);
	void OnNewCharacterBeginPlay();
	void SetIsFallOff(bool IsFallOff_0);
	void OnRep_IsFallOff();
	bool CanHandlerSignal();
	void ReceiveDestroyed();
	void SetResponsableState(bool IsResponsable);
	void SetActive(bool bInActive);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySignalHandlerActor">();
	}
	static class APySignalHandlerActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySignalHandlerActor>();
	}
};

}

