#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyStormCharacter

#include "Basic.hpp"

#include "Hero_1015_classes.hpp"


namespace SDK
{

// PythonClass PyStormCharacter.PyStormCharacter
// 0x0000 (0x18F0 - 0x18F0)
class APyStormCharacter : public AStormCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyStormCharacter">();
	}
	static class APyStormCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyStormCharacter>();
	}
};

}

