#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyTabData_1035

#include "Basic.hpp"

#include "PyTabData_1035_classes.hpp"


namespace SDK
{

// PythonFunction PyTabData_1035.PyTabData_1035.K2_Initialize
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyTabData_1035::K2_Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTabData_1035", "K2_Initialize");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTabData_1035.PyTabData_1035.K2_Shutdown
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyTabData_1035::K2_Shutdown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTabData_1035", "K2_Shutdown");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

