#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyTrainingPlayerStatistics

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// PythonClass PyTrainingPlayerStatistics.PyTrainingPlayerStatistics
// 0x0000 (0x0030 - 0x0030)
class UPyTrainingPlayerStatistics final : public UObject
{
public:
	void Initialize(class AMarvelPlayerState* player_state);
	void Shutdown();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTrainingPlayerStatistics">();
	}
	static class UPyTrainingPlayerStatistics* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTrainingPlayerStatistics>();
	}
};

}

