#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyVirtualCarActor

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyVirtualCarActor.PyMarvelVirtualCarActor
// 0x0000 (0x14A0 - 0x14A0)
class APyMarvelVirtualCarActor : public AMarvelVirtualCarActor
{
public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyMarvelVirtualCarActor">();
	}
	static class APyMarvelVirtualCarActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyMarvelVirtualCarActor>();
	}
};

}

