#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_HeroList_Card

#include "Basic.hpp"

#include "PyWidget_HeroList_CardBase_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_HeroList_Card.PyWidget_HeroList_Card
// 0x0000 (0x07A8 - 0x07A8)
class UPyWidget_HeroList_Card : public UPyWidget_HeroList_CardBase
{
public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();
	void SetIsHover(bool IsHovered_0);
	void SetIsDelayHovered(bool IsDelayHovered);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_HeroList_Card">();
	}
	static class UPyWidget_HeroList_Card* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_HeroList_Card>();
	}
};

}

