#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Clan_LeagueHistory

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Clan_LeagueHistory.ClanHonorData
// 0x0000 (0x0030 - 0x0030)
class UClanHonorData final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ClanHonorData">();
	}
	static class UClanHonorData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClanHonorData>();
	}
};

// PythonClass PyWidget_Clan_LeagueHistory.PyWidget_Clan_LeagueHistory
// 0x0010 (0x0628 - 0x0618)
class UPyWidget_Clan_LeagueHistory : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	class UTexture2D*                             ImgNoFilter;                                       // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgFilter;                                         // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Clan_LeagueHistory">();
	}
	static class UPyWidget_Clan_LeagueHistory* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Clan_LeagueHistory>();
	}
};

}

