#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Clan_ApplyEntry

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Clan_ApplyEntry.PyWidget_Clan_ApplyEntry.OnMouseEnter
// 0x00B8 (0x00B8 - 0x0000)
struct PyWidget_Clan_ApplyEntry_OnMouseEnter final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0080)(ConstParm, Parm, OutParm, ReferenceParm)
};

// PythonFunction PyWidget_Clan_ApplyEntry.PyWidget_Clan_ApplyEntry.OnMouseLeave
// 0x0080 (0x0080 - 0x0000)
struct PyWidget_Clan_ApplyEntry_OnMouseLeave final
{
public:
	struct FPointerEvent                          MouseEvent;                                        // 0x0000(0x0080)(ConstParm, Parm, OutParm, ReferenceParm)
};

}

