#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Recruit_PlayerIcon

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Recruit_PlayerIcon.PyWidget_Recruit_PlayerIcon
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Recruit_PlayerIcon : public UPyMarvelUserWidget
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Recruit_PlayerIcon">();
	}
	static class UPyWidget_Recruit_PlayerIcon* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Recruit_PlayerIcon>();
	}
};

}

