#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_MailPanel

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Marvel_structs.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_MailPanel.PyWidget_MailPanel
// 0x0590 (0x0BA8 - 0x0618)
class UPyWidget_MailPanel : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_611[0x3];                                      // 0x0611(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FMargin                                ItemPadding;                                       // 0x0614(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	float                                         TimeBetweenInsertion;                              // 0x0624(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AKEvent_DeleteMail;                                // 0x0628(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AKEvent_MarkMail;                                  // 0x0630(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AKEvent_UnmarkMail;                                // 0x0638(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AKEvent_NoMailToDelete;                            // 0x0640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        PageChangeTips;                                    // 0x0648(0x0110)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        GetRewardTips;                                     // 0x0758(0x0110)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        DeleteTips;                                        // 0x0868(0x0110)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        FavourTips;                                        // 0x0978(0x0110)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGuideTipsStyle                        UnfavourTips;                                      // 0x0A88(0x0110)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UInputAction*                           AttachmentFocusAction;                             // 0x0B98(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CountLimitOfHoverTips;                             // 0x0BA0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnBecomeTop();
	void OnBecomeNoneTop();
	void MarvelSetVisible(bool Visible);
	class UWidget* navigation_to_first_content(EUINavigation NavType);
	class UWidget* navigation_to_next_content(EUINavigation NavType);
	class UWidget* navigation_to_selected_mail_unit(EUINavigation NavType);
	class UWidget* navigation_to_content_center(EUINavigation NavType);
	class UWidget* navigation_from_center_to_content(EUINavigation NavType);
	void OnListviewEntryGenerated(class UUserWidget* EntryWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_MailPanel">();
	}
	static class UPyWidget_MailPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_MailPanel>();
	}
};

}

