#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_FriendsModular_V3

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_FriendsModular_V3.PyWidget_FriendsModular_V3
// 0x0140 (0x06F0 - 0x05B0)
class UPyWidget_FriendsModular_V3 : public UWidget_ListEntry
{
public:
	TArray<struct FLinearColor>                   TabStateColor;                                     // 0x05B0(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           TabPlayerState;                                    // 0x05C0(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           FriendsText;                                       // 0x05D0(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           PSFriendsText;                                     // 0x05E0(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           OnlyPSFriendsText;                                 // 0x05F0(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           AddFriendsText;                                    // 0x0600(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           SearchPlayerInBlacklistText;                       // 0x0610(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<class FText>                           ApplyText;                                         // 0x0620(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          NormalItem;                                        // 0x0630(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsFriend;                                          // 0x0631(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsApply;                                           // 0x0632(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsAdd;                                             // 0x0633(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsSearch;                                          // 0x0634(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsDelete;                                          // 0x0635(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_636[0x2];                                      // 0x0636(0x0002)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         ApplyTime;                                         // 0x0638(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_63C[0x4];                                      // 0x063C(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	class FText                                   AddBtnTips;                                        // 0x0640(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   AcceptAdd;                                         // 0x0658(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   RefuceAdd;                                         // 0x0670(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   InviteTips;                                        // 0x0688(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   ApplyTips;                                         // 0x06A0(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   TeamText;                                          // 0x06B8(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         TestState;                                         // 0x06D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6D4[0x4];                                      // 0x06D4(0x0004)(Fixing Size After Last Property [ Chaos Dumper ])
	class UAkAudioEvent*                          AkEvent_OpenSelectBox;                             // 0x06D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_DeleteFriendsPanel;                        // 0x06E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                Item_Object;                                       // 0x06E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();
	void OnListItemObjectSet(class UObject* ItemObject);
	void SetIsDelete(bool IsDelete_0);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_FriendsModular_V3">();
	}
	static class UPyWidget_FriendsModular_V3* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_FriendsModular_V3>();
	}
};

}

