#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_PingPanel

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_PingPanel.PyWidget_PingPanel
// 0x0008 (0x05F8 - 0x05F0)
class UPyWidget_PingPanel : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	class UPyDataAsset_Ping*                      PingInfoDataAsset;                                 // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_PingPanel">();
	}
	static class UPyWidget_PingPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_PingPanel>();
	}
};

}

