#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_MallDetail

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_MallDetail.PyWidget_MallDetail_ConfirmBtn.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_MallDetail_ConfirmBtn_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_MallDetail.PyWidget_MallDetail.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_MallDetail_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_MallDetail.PyWidget_MallDetail.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_MallDetail_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

