#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar.PyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar">();
	}
	static class UPyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_HomeEntrance_Activity_Item_S1SeasonStory_TaskPbar>();
	}
};

}

