#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Common_NavigationBar_Button

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Common_NavigationBar_Button.PyWidget_Common_NavigationBar_Button.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Common_NavigationBar_Button_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_Common_NavigationBar_Button.PyWidget_Common_NavigationBar_Button.SetIsHover
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Common_NavigationBar_Button_SetIsHover final
{
public:
	bool                                          IsHover_0;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

