#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_BattlePass_Main

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_BattlePass_Main.PyWidget_BattlePass_Main
// 0x0008 (0x0620 - 0x0618)
class UPyWidget_BattlePass_Main : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	class UMarvelCanvasPanel*                     CanvasPanel_Main;                                  // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BattlePass_Main">();
	}
	static class UPyWidget_BattlePass_Main* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BattlePass_Main>();
	}
};

}

