#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_MailContent

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_MailContent.PyWidget_MailContent
// 0x0028 (0x03E0 - 0x03B8)
class UPyWidget_MailContent : public UUserWidget
{
public:
	struct FMargin                                ItemPadding;                                       // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class UDataTable*                             LinkImgDataTable;                                  // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMargin                                ImagePadding;                                      // 0x03D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_MailContent">();
	}
	static class UPyWidget_MailContent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_MailContent>();
	}
};

// PythonClass PyWidget_MailContent.PyWidget_MailSurveyBtn
// 0x0000 (0x03B8 - 0x03B8)
class UPyWidget_MailSurveyBtn : public UUserWidget
{
public:
	void OnInitialized();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_MailSurveyBtn">();
	}
	static class UPyWidget_MailSurveyBtn* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_MailSurveyBtn>();
	}
};

}

