#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_GalleryBook_Card

#include "Basic.hpp"

#include "PyWidget_Button_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card
// 0x0038 (0x0788 - 0x0750)
class UPyWidget_GalleryBook_Card : public UPyWidget_Button
{
public:
	TMulticastInlineDelegate<void(int32 BookIndex, const class FString& BookItemID)> OnGalleryBookClicked;                              // 0x0750(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 BookIndex, const class FString& BookItemID, bool IsHover)> OnGalleryBookHovered;                              // 0x0760(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(bool IsPressed)> OnGalleryBookPressed;                              // 0x0770(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	class UTexture2D*                             EmptyCardTexture;                                  // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Destruct();
	void MarvelSetVisible(bool Visible);
	void OnAnimationStarted(const class UWidgetAnimation* Animation);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void SetIsHover(bool IsHover_0);
	void SetBtnIsPressed(bool IsBtnPressed_0);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_GalleryBook_Card">();
	}
	static class UPyWidget_GalleryBook_Card* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_GalleryBook_Card>();
	}
};

}

