#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Mall_PageList_Row

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Mall_PageList_Row.PyWidget_Mall_PageList_Row
// 0x0050 (0x0640 - 0x05F0)
class UPyWidget_Mall_PageList_Row : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	TArray<class UTexture2D*>                     PreviewBGMaskList;                                 // 0x05F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class UTexture2D*>                     PreviewItemMaskList;                               // 0x0600(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class UTexture2D*>                     PreviewBGMaskList_Higher;                          // 0x0610(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class UTexture2D*>                     PreviewItemMaskList_Higher;                        // 0x0620(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class UTexture2D*>                     DisplayMaskList;                                   // 0x0630(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void MarvelSetVisible(bool Visible);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Mall_PageList_Row">();
	}
	static class UPyWidget_Mall_PageList_Row* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Mall_PageList_Row>();
	}
};

// PythonClass PyWidget_Mall_PageList_Row.PyWidget_Mall_PageList_Row_SeriesTag
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Mall_PageList_Row_SeriesTag : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Mall_PageList_Row_SeriesTag">();
	}
	static class UPyWidget_Mall_PageList_Row_SeriesTag* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Mall_PageList_Row_SeriesTag>();
	}
};

}

