#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Mall_BundlePageList_Panel

#include "Basic.hpp"

#include "PyWidget_Mall_PageListPanel_Base_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Mall_BundlePageList_Panel.PyWidget_Mall_BundlePageList_Panel
// 0x0000 (0x0618 - 0x0618)
class UPyWidget_Mall_BundlePageList_Panel : public UPyWidget_Mall_PageListPanel_Base
{
public:
	bool                                          NeedPreview;                                       // 0x0611(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_612[0x2];                                      // 0x0612(0x0002)(Fixing Size After Last Property [ Chaos Dumper ])
	int32                                         Preview_TurnTOPage;                                // 0x0614(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Mall_BundlePageList_Panel">();
	}
	static class UPyWidget_Mall_BundlePageList_Panel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Mall_BundlePageList_Panel>();
	}
};

}

