#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_MallChildPanel

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_MallChildPanel.PyWidget_MallChildPanel.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_MallChildPanel_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

