#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Secondary_PopupUnit

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_PopupUnit.PyWidget_Secondary_PopupUnit
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Secondary_PopupUnit : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_PopupUnit">();
	}
	static class UPyWidget_Secondary_PopupUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_PopupUnit>();
	}
};

}

