#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_LeagueMRC_ParticipationTab

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_LeagueMRC_ParticipationTab.PyWidget_LeagueMRC_ParticipationTab
// 0x0040 (0x0630 - 0x05F0)
class UPyWidget_LeagueMRC_ParticipationTab : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	class FText                                   TabName;                                           // 0x05F0(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FSlateColor                            ColorNormal;                                       // 0x0608(0x0014)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FSlateColor                            ColorHover;                                        // 0x061C(0x0014)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LeagueMRC_ParticipationTab">();
	}
	static class UPyWidget_LeagueMRC_ParticipationTab* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LeagueMRC_ParticipationTab>();
	}
};

}

