#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_LeagueMRCSignUpCard

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_LeagueMRCSignUpCard.PyWidget_LeagueMRCSignUpCard
// 0x0060 (0x0650 - 0x05F0)
class UPyWidget_LeagueMRCSignUpCard : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x3];                                      // 0x05E9(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FSlateColor                            RegionTextColorHover;                              // 0x05EC(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            RegionTextColorCommon;                             // 0x0600(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            TimeTextColorHover;                                // 0x0614(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            OpenSignUpTimeTextColorCommon;                     // 0x0628(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            StopSignUpTimeTextColorCommon;                     // 0x063C(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LeagueMRCSignUpCard">();
	}
	static class UPyWidget_LeagueMRCSignUpCard* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LeagueMRCSignUpCard>();
	}
};

// PythonClass PyWidget_LeagueMRCSignUpCard.PyWidget_LeagueMRCSignUpCardTag
// 0x0018 (0x0608 - 0x05F0)
class UPyWidget_LeagueMRCSignUpCardTag : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Chaos Dumper ])
	class FText                                   TagContent;                                        // 0x05F0(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LeagueMRCSignUpCardTag">();
	}
	static class UPyWidget_LeagueMRCSignUpCardTag* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LeagueMRCSignUpCardTag>();
	}
};

}

