#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_BattleResultCommonV3

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_BattleResultCommonV3.PyWidget_HeroUsedV3
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_HeroUsedV3 final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_HeroUsedV3">();
	}
	static class UPyWidget_HeroUsedV3* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_HeroUsedV3>();
	}
};

// PythonClass PyWidget_BattleResultCommonV3.PyWidget_BattleResultMedalTipsUnit
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_BattleResultMedalTipsUnit : public UPyMarvelUserWidget
{
public:
	void OnIconLoaded(class UObject* Img_Picture);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BattleResultMedalTipsUnit">();
	}
	static class UPyWidget_BattleResultMedalTipsUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BattleResultMedalTipsUnit>();
	}
};

}

