#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_Secondary_Blacklist

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_Blacklist.PyWidget_Secondary_Blacklist
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Secondary_Blacklist final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_Blacklist">();
	}
	static class UPyWidget_Secondary_Blacklist* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_Blacklist>();
	}
};

// PythonClass PyWidget_Secondary_Blacklist.PyWidget_Blacklist_Item
// 0x0010 (0x0600 - 0x05F0)
class UPyWidget_Blacklist_Item : public UPyMarvelUserWidget
{
public:
	bool                                          IsAvoidTeam;                                       // 0x05E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5EA[0x6];                                      // 0x05EA(0x0006)(Fixing Size After Last Property [ Chaos Dumper ])
	TMulticastInlineDelegate<void()>              AfterSelfDeleted;                                  // 0x05F0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Blacklist_Item">();
	}
	static class UPyWidget_Blacklist_Item* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Blacklist_Item>();
	}
};

}

