#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: PyWidget_SettingPageBase

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_SettingPageBase.PyWidget_SettingPageBase.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SettingPageBase_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

