#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: ResurrectionAbility_102402_BP

#include "Basic.hpp"

#include "Hero_1024_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ResurrectionAbility_102402_BP.ResurrectionAbility_102402_BP_C
// 0x0000 (0x11A0 - 0x11A0)
class UResurrectionAbility_102402_BP_C final : public UResurrectionAbility_10240201
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ResurrectionAbility_102402_BP_C">();
	}
	static class UResurrectionAbility_102402_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UResurrectionAbility_102402_BP_C>();
	}
};

}

