#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: RichTextLink_RegulationRuleTips_BP

#include "Basic.hpp"

#include "PyHyperlinkDecorator_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RichTextLink_RegulationRuleTips_BP.RichTextLink_RegulationRuleTips_BP_C
// 0x0000 (0x0F20 - 0x0F20)
class URichTextLink_RegulationRuleTips_BP_C final : public UPyHyperlinkDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RichTextLink_RegulationRuleTips_BP_C">();
	}
	static class URichTextLink_RegulationRuleTips_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URichTextLink_RegulationRuleTips_BP_C>();
	}
};

}

