#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: RichTextPlayerNameOut_BP

#include "Basic.hpp"

#include "PyHyperlinkDecorator_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RichTextPlayerNameOut_BP.RichTextPlayerNameOut_BP_C
// 0x0000 (0x0F20 - 0x0F20)
class URichTextPlayerNameOut_BP_C final : public UPyHyperlinkDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RichTextPlayerNameOut_BP_C">();
	}
	static class URichTextPlayerNameOut_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URichTextPlayerNameOut_BP_C>();
	}
};

}

