#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: RichTextMailWidget_BP

#include "Basic.hpp"

#include "PyRichTextCustomWidgetDecorator_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RichTextMailWidget_BP.RichTextMailWidget_BP_C
// 0x0000 (0x0050 - 0x0050)
class URichTextMailWidget_BP_C final : public UPyRichTextCustomWidgetDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RichTextMailWidget_BP_C">();
	}
	static class URichTextMailWidget_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URichTextMailWidget_BP_C>();
	}
};

}

