#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: RichTextHyperlink_Chat_BP

#include "Basic.hpp"

#include "PyHyperlinkDecorator_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RichTextHyperlink_Chat_BP.RichTextHyperlink_Chat_BP_C
// 0x0000 (0x0F20 - 0x0F20)
class URichTextHyperlink_Chat_BP_C final : public UPyHyperlinkDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RichTextHyperlink_Chat_BP_C">();
	}
	static class URichTextHyperlink_Chat_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URichTextHyperlink_Chat_BP_C>();
	}
};

}

