#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Stealth_101641_Phantom_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Stealth_101641_Phantom_BP.Stealth_101641_Phantom_BP_C
// 0x0000 (0x1320 - 0x1320)
class UStealth_101641_Phantom_BP_C final : public UMarvelStealthAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Stealth_101641_Phantom_BP_C">();
	}
	static class UStealth_101641_Phantom_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStealth_101641_Phantom_BP_C>();
	}
};

}

