#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: StencilSettingsBP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StencilSettingsBP.StencilSettingsBP_C
// 0x0000 (0x00F8 - 0x00F8)
class UStencilSettingsBP_C final : public UStencilSettings
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StencilSettingsBP_C">();
	}
	static class UStencilSettingsBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStencilSettingsBP_C>();
	}
};

}

