#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Summoned_10423101_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Summoned_10423101_BP.Summoned_10423101_BP_C
// 0x0020 (0x08E0 - 0x08C0)
class ASummoned_10423101_BP_C final : public AMarvelSummonerBase
{
public:
	class UStaticMeshComponent*                   BlockProjectileCollision1;                         // 0x08C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BlockProjectileCollision;                          // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   ShiledCollision;                                   // 0x08D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Summoned_10423101_BP_C">();
	}
	static class ASummoned_10423101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10423101_BP_C>();
	}
};

}

