#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: SummonedComp_10424102_BP

#include "Basic.hpp"

#include "PyAbility_104241_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SummonedComp_10424102_BP.SummonedComp_10424102_BP_C
// 0x0000 (0x0CA0 - 0x0CA0)
class USummonedComp_10424102_BP_C final : public UPySummonedComp_10424102
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SummonedComp_10424102_BP_C">();
	}
	static class USummonedComp_10424102_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USummonedComp_10424102_BP_C>();
	}
};

}

