#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Summoned_10296101_BP

#include "Basic.hpp"

#include "Hero_1029_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Summoned_10296101_BP.Summoned_10296101_BP_C
// 0x0010 (0x08D0 - 0x08C0)
class ASummoned_10296101_BP_C : public ASummoned_102961
{
public:
	class USummonedMovementComponent*             SummonedMovement;                                  // 0x08C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCharacterCollisionComponent*           CharacterCollision;                                // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Summoned_10296101_BP_C">();
	}
	static class ASummoned_10296101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10296101_BP_C>();
	}
};

}

