#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Summoned_V2_10455101_BP

#include "Basic.hpp"

#include "PyAbility_104551_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Summoned_V2_10455101_BP.Summoned_V2_10455101_BP_C
// 0x0010 (0x1060 - 0x1050)
class ASummoned_V2_10455101_BP_C : public APySummoned_10455101
{
public:
	class UMarvelHitShape_Capsule*                HitBody;                                           // 0x1050(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USummonedMovementComponent*             SummonedMovement;                                  // 0x1058(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Summoned_V2_10455101_BP_C">();
	}
	static class ASummoned_V2_10455101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_V2_10455101_BP_C>();
	}
};

}

