#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: TurnCharacterAndCameraAbility_103631

#include "Basic.hpp"

#include "Hero_1036_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TurnCharacterAndCameraAbility_103631.TurnCharacterAndCameraAbility_103631_C
// 0x0000 (0x1120 - 0x1120)
class UTurnCharacterAndCameraAbility_103631_C final : public UMarvelTurnCharacterAndCameraAbility_103631
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TurnCharacterAndCameraAbility_103631_C">();
	}
	static class UTurnCharacterAndCameraAbility_103631_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTurnCharacterAndCameraAbility_103631_C>();
	}
};

}

