#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: UIC_LevelTransitionBP

#include "Basic.hpp"

#include "PyUIC_LevelTransition_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UIC_LevelTransitionBP.UIC_LevelTransitionBP_C
// 0x0000 (0x0030 - 0x0030)
class UUIC_LevelTransitionBP_C final : public UPyUIC_LevelTransition
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UIC_LevelTransitionBP_C">();
	}
	static class UUIC_LevelTransitionBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIC_LevelTransitionBP_C>();
	}
};

}

