#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: UIParticle

#include "Basic.hpp"


namespace SDK::Params
{

// Function UIParticle.UIParticle.SetPlayParticle
// 0x0001 (0x0001 - 0x0000)
struct UIParticle_SetPlayParticle final
{
public:
	bool                                          InPlayParticle;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function UIParticle.UIParticleEmitter.SetPlayParticle
// 0x0001 (0x0001 - 0x0000)
struct UIParticleEmitter_SetPlayParticle final
{
public:
	bool                                          InPlayParticle;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

