#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: UISettingReticleColorSettingHandlerBP

#include "Basic.hpp"

#include "Reticle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UISettingReticleColorSettingHandlerBP.UISettingReticleColorSettingHandlerBP_C
// 0x0000 (0x0038 - 0x0038)
class UUISettingReticleColorSettingHandlerBP_C final : public UUISettingReticleColorSettingHandler
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UISettingReticleColorSettingHandlerBP_C">();
	}
	static class UUISettingReticleColorSettingHandlerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingReticleColorSettingHandlerBP_C>();
	}
};

}

