#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_CommonAwardPreview

#include "Basic.hpp"

#include "PyWidget_Common_Preview_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CommonAwardPreview.WBP_CommonAwardPreview_C
// 0x0010 (0x0658 - 0x0648)
class UWBP_CommonAwardPreview_C final : public UPyWidget_Common_Preview
{
public:
	class UWBP_Common_ItemData_C*                 ItemData;                                          // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CommonItemPanel_C*                 WBP_CommonItemPanel;                               // 0x0650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CommonAwardPreview_C">();
	}
	static class UWBP_CommonAwardPreview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CommonAwardPreview_C>();
	}
};

}

