#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Home_Activity_ToggleTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyWidget_HomeEntrance_Advertisement_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Home_Activity_ToggleTab.WBP_Home_Activity_ToggleTab_C
// 0x0030 (0x0620 - 0x05F0)
class UWBP_Home_Activity_ToggleTab_C final : public UPyWidget_HomeEntrance_Advertisement_Container_Nav_Widget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMarvelButton*                          Btn_Item;                                          // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Tab_Hover;                                     // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Tab_Normal;                                    // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Tab_Select;                                    // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsSelect;                                          // 0x0618(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Home_Activity_ToggleTab(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Home_Activity_ToggleTab_C">();
	}
	static class UWBP_Home_Activity_ToggleTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Home_Activity_ToggleTab_C>();
	}
};

}

