#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_TeamUp_Switch_Btn

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_TeamUp_Switch_Btn.WBP_TeamUp_Switch_Btn_C.ExecuteUbergraph_WBP_TeamUp_Switch_Btn
// 0x0010 (0x0010 - 0x0000)
struct WBP_TeamUp_Switch_Btn_C_ExecuteUbergraph_WBP_TeamUp_Switch_Btn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Chaos Dumper ])
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_TeamUp_Switch_Btn.WBP_TeamUp_Switch_Btn_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_TeamUp_Switch_Btn_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

