#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_BattlePass_NavigationBar_PinTop_Button

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_BattlePass_NavigationBar_PinTop_Button.WBP_BattlePass_NavigationBar_PinTop_Button_C.ExecuteUbergraph_WBP_BattlePass_NavigationBar_PinTop_Button
// 0x0004 (0x0004 - 0x0000)
struct WBP_BattlePass_NavigationBar_PinTop_Button_C_ExecuteUbergraph_WBP_BattlePass_NavigationBar_PinTop_Button final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

