#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Secondary_MissionPanel

#include "Basic.hpp"

#include "PyWidget_Secondary_MissionPanel_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Secondary_MissionPanel.WBP_Secondary_MissionPanel_C
// 0x0018 (0x0630 - 0x0618)
class UWBP_Secondary_MissionPanel_C final : public UPyWidget_Secondary_MissionPanel
{
public:
	class UWBP_Common_Bg_C*                       WBP_Common_Bg;                                     // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_NavigationBar_LV2_C*        WBP_Common_NavigationBar;                          // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Mission_Panel_V2_C*                WBP_Mission_Panel_V2;                              // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Secondary_MissionPanel_C">();
	}
	static class UWBP_Secondary_MissionPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Secondary_MissionPanel_C>();
	}
};

}

