#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Secondary_ApplyToJoin

#include "Basic.hpp"

#include "PyWidget_Secondary_Apply_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Secondary_ApplyToJoin.WBP_Secondary_ApplyToJoin_C
// 0x0010 (0x0600 - 0x05F0)
class UWBP_Secondary_ApplyToJoin_C final : public UPyWidget_Secondary_Apply
{
public:
	class UMarvelImage*                           img_bg;                                            // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelMultiLineEditableText*           MultiLineText_Content;                             // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Secondary_ApplyToJoin_C">();
	}
	static class UWBP_Secondary_ApplyToJoin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Secondary_ApplyToJoin_C>();
	}
};

}

