#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Common_VX_LineAngle

#include "Basic.hpp"

#include "PyWidget_Common_LineAngle_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Common_VX_LineAngle.WBP_Common_VX_LineAngle_C
// 0x0020 (0x0630 - 0x0610)
class UWBP_Common_VX_LineAngle_C final : public UPyWidget_Common_LineAngle
{
public:
	class UWBP_Common_BgAngle_C*                  BgAngle;                                           // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelButton*                          Btn_ListHover;                                     // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Btn;                                       // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_VX_Line_C*                  VX_Line;                                           // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Common_VX_LineAngle_C">();
	}
	static class UWBP_Common_VX_LineAngle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Common_VX_LineAngle_C>();
	}
};

}

