#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Mall_Text_Tag

#include "Basic.hpp"

#include "PyWidget_Mall_Bundle_Tag_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Mall_Text_Tag.WBP_Mall_Text_Tag_C
// 0x0010 (0x0630 - 0x0620)
class UWBP_Mall_Text_Tag_C final : public UPyWidget_Mall_Bundle_Normal_Tag
{
public:
	class UImage*                                 Image_Tag_Bg;                                      // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_Tag;                                          // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnPaint(struct FPaintContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Mall_Text_Tag_C">();
	}
	static class UWBP_Mall_Text_Tag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Mall_Text_Tag_C>();
	}
};

}

