#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_BattlePass_Main

#include "Basic.hpp"

#include "PyWidget_BattlePass_Main_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_BattlePass_Main.WBP_BattlePass_Main_C
// 0x0000 (0x0620 - 0x0620)
class UWBP_BattlePass_Main_C final : public UPyWidget_BattlePass_Main
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_BattlePass_Main_C">();
	}
	static class UWBP_BattlePass_Main_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BattlePass_Main_C>();
	}
};

}

