#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Lobby_League

#include "Basic.hpp"

#include "PyWidget_LeagueLobbyPanel_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Lobby_League.WBP_Lobby_League_C
// 0x0018 (0x0638 - 0x0620)
class UWBP_Lobby_League_C final : public UPyWidget_LeagueLobbyPanel
{
public:
	class ULazyWidget*                            Lazy_League_MRC;                                   // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULazyWidget*                            Lazy_League_RegularLobby;                          // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULazyWidget*                            Lazy_Team_Main;                                    // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Lobby_League_C">();
	}
	static class UWBP_Lobby_League_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Lobby_League_C>();
	}
};

}

