#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Regulations_JP_Tips

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Regulations_JP_Tips.WBP_Regulations_JP_Tips_C
// 0x0008 (0x03C0 - 0x03B8)
class UWBP_Regulations_JP_Tips_C final : public UUserWidget
{
public:
	class UMarvelRichTextBlock*                   RichText_Regulations_JP;                           // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Regulations_JP_Tips_C">();
	}
	static class UWBP_Regulations_JP_Tips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Regulations_JP_Tips_C>();
	}
};

}

