#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Common_Btn_WYG

#include "Basic.hpp"

#include "Enum_Common_BtnStyle_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_Common_Btn_WYG.WBP_Common_Btn_WYG_C.ExecuteUbergraph_WBP_Common_Btn_WYG
// 0x2060 (0x2060 - 0x0000)
struct WBP_Common_Btn_WYG_C_ExecuteUbergraph_WBP_Common_Btn_WYG final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_Common_BtnStyle                          Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0xB];                                        // 0x0005(0x000B)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FButtonStyle                           Temp_struct_Variable;                              // 0x0010(0x0400)(ConstParm)
	struct FButtonStyle                           Temp_struct_Variable_1;                            // 0x0410(0x0400)(ConstParm)
	struct FButtonStyle                           Temp_struct_Variable_2;                            // 0x0810(0x0400)(ConstParm)
	Enum_Common_BtnStyle                          Temp_byte_Variable_1;                              // 0x0C10(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C11[0xF];                                      // 0x0C11(0x000F)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FButtonStyle                           Temp_struct_Variable_3;                            // 0x0C20(0x0400)(ConstParm)
	struct FButtonStyle                           Temp_struct_Variable_4;                            // 0x1020(0x0400)(ConstParm)
	struct FButtonStyle                           Temp_struct_Variable_5;                            // 0x1420(0x0400)(ConstParm)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x1820(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1821[0xF];                                     // 0x1821(0x000F)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FButtonStyle                           K2Node_Select_Default;                             // 0x1830(0x0400)(ConstParm)
	class FText                                   K2Node_CustomEvent_Btn_Name;                       // 0x1C30(0x0018)()
	uint8                                         Pad_1C48[0x8];                                     // 0x1C48(0x0008)(Fixing Size After Last Property [ Chaos Dumper ])
	struct FButtonStyle                           K2Node_Select_Default_1;                           // 0x1C50(0x0400)(ConstParm)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x2050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x2054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_Common_Btn_WYG.WBP_Common_Btn_WYG_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Common_Btn_WYG_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_Common_Btn_WYG.WBP_Common_Btn_WYG_C.SetBtnName
// 0x0018 (0x0018 - 0x0000)
struct WBP_Common_Btn_WYG_C_SetBtnName final
{
public:
	class FText                                   Btn_Name;                                          // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

}

