#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Team_CreateClan_CoolingTips

#include "Basic.hpp"

#include "PyWidget_Clan_ClanCreate_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Team_CreateClan_CoolingTips.WBP_Team_CreateClan_CoolingTips_C
// 0x0000 (0x05F8 - 0x05F8)
class UWBP_Team_CreateClan_CoolingTips_C final : public UPyWidget_Clan_ClanCreateCoolingItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Team_CreateClan_CoolingTips_C">();
	}
	static class UWBP_Team_CreateClan_CoolingTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Team_CreateClan_CoolingTips_C>();
	}
};

}

