#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WBP_Setting_OptionEntryTitle

#include "Basic.hpp"

#include "PyWidget_SettingOptionEntry_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Setting_OptionEntryTitle.WBP_Setting_OptionEntryTitle_C
// 0x0000 (0x0630 - 0x0630)
class UWBP_Setting_OptionEntryTitle_C final : public UPyWidget_SettingOptionEntryTitle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Setting_OptionEntryTitle_C">();
	}
	static class UWBP_Setting_OptionEntryTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Setting_OptionEntryTitle_C>();
	}
};

}

