#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: WC_DebugInfoBP

#include "Basic.hpp"

#include "PyWidget_DebugInfo_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WC_DebugInfoBP.WC_DebugInfoBP_C
// 0x0000 (0x0AC0 - 0x0AC0)
class UWC_DebugInfoBP_C final : public UPyWC_DebugInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WC_DebugInfoBP_C">();
	}
	static class UWC_DebugInfoBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWC_DebugInfoBP_C>();
	}
};

}

