#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Weapon_PunisherTurret

#include "Basic.hpp"

#include "Hero_1014_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_PunisherTurret.Weapon_PunisherTurret_C
// 0x0000 (0x0C80 - 0x0C80)
class AWeapon_PunisherTurret_C final : public AWeapon_101406
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_PunisherTurret_C">();
	}
	static class AWeapon_PunisherTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_PunisherTurret_C>();
	}
};

}

