#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Weapon_PunisherElectronGun

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_PunisherElectronGun.Weapon_PunisherElectronGun_C
// 0x0000 (0x0C80 - 0x0C80)
class AWeapon_PunisherElectronGun_C final : public AShootingWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_PunisherElectronGun_C">();
	}
	static class AWeapon_PunisherElectronGun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_PunisherElectronGun_C>();
	}
};

}

