#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Weapon_PunisherShotgun

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_PunisherShotgun.Weapon_PunisherShotgun_C
// 0x0000 (0x0C80 - 0x0C80)
class AWeapon_PunisherShotgun_C final : public AShootingWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_PunisherShotgun_C">();
	}
	static class AWeapon_PunisherShotgun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_PunisherShotgun_C>();
	}
};

}

