#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: Weapon_MoonKnight_10302101

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_MoonKnight_10302101.Weapon_MoonKnight_10302101_C
// 0x0000 (0x0C80 - 0x0C80)
class AWeapon_MoonKnight_10302101_C final : public AShootingWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_MoonKnight_10302101_C">();
	}
	static class AWeapon_MoonKnight_10302101_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_MoonKnight_10302101_C>();
	}
};

}

