#pragma once

/*
* SDK generated by Chaos Dumper (Based off Dumper-7)
*

*/

// Package: XeFGBlueprint

#include "Basic.hpp"


namespace SDK
{

// Enum XeFGBlueprint.EXeFGMode
// NumValues: 0x0003
enum class EXeFGMode : uint8
{
	Off                                      = 0,
	On                                       = 1,
	EXeFGMode_MAX                            = 2,
};

}

